from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("kind", models.CharField(choices=[("ORGANIZATION", "Organization"), ("DIVISION", "Division / Chapter"), ("TEAM", "Team"), ("CLUB", "Club"), ("COMMUNITY", "Community"), ("HOUSEHOLD", "Household"), ("OTHER", "Other")], default="COMMUNITY", max_length=20)),
                ("visibility", models.CharField(choices=[("PUBLIC", "Public"), ("PRIVATE", "Private"), ("INVITE_ONLY", "Invite only")], default="PRIVATE", max_length=20)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=80)),
                ("logo_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_groups_created", to=settings.AUTH_USER_MODEL)),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="children", to="platform_social.socialgroup")),
            ],
            options={"ordering": ("name", "id")},
        ),
        migrations.CreateModel(
            name="SocialEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="America/Chicago", max_length=64)),
                ("venue_name", models.CharField(blank=True, max_length=180)),
                ("address_line1", models.CharField(blank=True, max_length=220)),
                ("address_line2", models.CharField(blank=True, max_length=220)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=80)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="US", max_length=2)),
                ("entry_amount_cents", models.PositiveIntegerField(default=0)),
                ("payment_due_at", models.DateTimeField(blank=True, null=True)),
                ("prizes", models.TextField(blank=True)),
                ("rules", models.TextField(blank=True)),
                ("flyer_url", models.URLField(blank=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published"), ("CANCELLED", "Cancelled"), ("COMPLETED", "Completed")], default="DRAFT", max_length=12)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_events_created", to=settings.AUTH_USER_MODEL)),
                ("organizer_group", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="platform_social.socialgroup")),
            ],
            options={"ordering": ("start_at", "id")},
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("total_amount_cents", models.PositiveIntegerField(default=0)),
                ("split_method", models.CharField(choices=[("EQUAL", "Equal"), ("CUSTOM", "Custom"), ("QUANTITY", "Quantity based"), ("OPTIONAL", "Optional contribution"), ("REQUIRED", "Required contribution")], default="EQUAL", max_length=12)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("OPEN", "Open"), ("FUNDED", "Funded"), ("CLOSED", "Closed"), ("CANCELLED", "Cancelled")], default="DRAFT", max_length=12)),
                ("platform_fee_bps", models.PositiveSmallIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_collections_created", to=settings.AUTH_USER_MODEL)),
                ("event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="collections", to="platform_social.socialevent")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="collections", to="platform_social.socialgroup")),
            ],
            options={"ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted"), ("DECLINED", "Declined"), ("BLOCKED", "Blocked")], default="PENDING", max_length=12)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_connections_received", to=settings.AUTH_USER_MODEL)),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_connections_sent", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("OWNER", "Owner"), ("DIRECTOR", "Director"), ("MANAGER", "Manager / Coach"), ("MEMBER", "Member")], default="MEMBER", max_length=12)),
                ("status", models.CharField(choices=[("INVITED", "Invited"), ("ACTIVE", "Active"), ("DECLINED", "Declined"), ("REMOVED", "Removed")], default="INVITED", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="platform_social.socialgroup")),
                ("invited_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="social_membership_invites_sent", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_group_memberships", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="GroupEventInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted"), ("DECLINED", "Declined")], default="PENDING", max_length=12)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="group_invitations", to="platform_social.socialevent")),
                ("invited_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_event_invites_sent", to=settings.AUTH_USER_MODEL)),
                ("responded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="social_event_invites_responded", to=settings.AUTH_USER_MODEL)),
                ("target_group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="event_invitations", to="platform_social.socialgroup")),
            ],
        ),
        migrations.CreateModel(
            name="EventMemberResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("response", models.CharField(choices=[("PENDING", "Pending"), ("YES", "Yes"), ("MAYBE", "Maybe"), ("NO", "No")], default="PENDING", max_length=10)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="member_responses", to="platform_social.socialevent")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="event_member_responses", to="platform_social.socialgroup")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_event_responses", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CollectionShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount_due_cents", models.PositiveIntegerField(default=0)),
                ("amount_paid_cents", models.PositiveIntegerField(default=0)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("DUE", "Due"), ("PARTIAL", "Partially paid"), ("PAID", "Paid"), ("WAIVED", "Waived")], default="DUE", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("collection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shares", to="platform_social.collection")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_collection_shares", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(model_name="socialgroup", index=models.Index(fields=["parent", "is_active"], name="social_group_parent_active")),
        migrations.AddIndex(model_name="socialevent", index=models.Index(fields=["organizer_group", "status", "start_at"], name="social_event_group_start")),
        migrations.AddIndex(model_name="collection", index=models.Index(fields=["group", "status"], name="social_collection_status")),
        migrations.AddIndex(model_name="connection", index=models.Index(fields=["sender", "status"], name="social_conn_sender_status")),
        migrations.AddIndex(model_name="connection", index=models.Index(fields=["recipient", "status"], name="social_conn_recipient_status")),
        migrations.AddConstraint(model_name="connection", constraint=models.UniqueConstraint(fields=("sender", "recipient"), name="social_unique_connection_direction")),
        migrations.AddConstraint(model_name="connection", constraint=models.CheckConstraint(condition=~models.Q(sender=models.F("recipient")), name="social_no_self_connection")),
        migrations.AddIndex(model_name="groupmembership", index=models.Index(fields=["group", "status", "role"], name="social_group_member_lookup")),
        migrations.AddConstraint(model_name="groupmembership", constraint=models.UniqueConstraint(fields=("group", "user"), name="social_unique_group_member")),
        migrations.AddIndex(model_name="groupeventinvitation", index=models.Index(fields=["target_group", "status"], name="social_event_invite_status")),
        migrations.AddConstraint(model_name="groupeventinvitation", constraint=models.UniqueConstraint(fields=("event", "target_group"), name="social_unique_event_group_invite")),
        migrations.AddIndex(model_name="eventmemberresponse", index=models.Index(fields=["event", "group", "response"], name="social_event_response_lookup")),
        migrations.AddConstraint(model_name="eventmemberresponse", constraint=models.UniqueConstraint(fields=("event", "group", "user"), name="social_unique_member_event_response")),
        migrations.AddIndex(model_name="collectionshare", index=models.Index(fields=["collection", "status"], name="social_share_status")),
        migrations.AddConstraint(model_name="collectionshare", constraint=models.UniqueConstraint(fields=("collection", "user"), name="social_unique_collection_share")),
    ]
