import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pm_workspace", "0003_pmproject_pmprojectupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PMUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=80)),
                ("bedrooms", models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ("bathrooms", models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ("square_feet", models.PositiveIntegerField(blank=True, null=True)),
                ("market_rent", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("availability", models.CharField(choices=[("AVAILABLE", "Available"), ("OCCUPIED", "Occupied"), ("NOTICE_GIVEN", "Notice given"), ("MAKE_READY", "Make ready"), ("CONSTRUCTION", "Under construction"), ("OFF_MARKET", "Off market")], default="AVAILABLE", max_length=24)),
                ("available_date", models.DateField(blank=True, null=True)),
                ("accepts_section8", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="units", to="pm_workspace.pmproperty")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="units", to="pm_workspace.pmworkspace")),
            ],
            options={"ordering": ["property__name", "label"]},
        ),
        migrations.CreateModel(
            name="PMProspect",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("stage", models.CharField(choices=[("LEAD", "Lead"), ("APPLICATION_SENT", "Application sent"), ("APPLICATION_RECEIVED", "Application received"), ("SCREENING", "Screening"), ("APPROVED", "Approved"), ("SHOWING_SCHEDULED", "Showing scheduled"), ("READY_FOR_ONBOARDING", "Ready for onboarding"), ("CONVERTED", "Converted to tenant"), ("DECLINED", "Declined"), ("WITHDRAWN", "Withdrawn")], default="LEAD", max_length=32)),
                ("section8_requested", models.BooleanField(default=False)),
                ("voucher_authority", models.CharField(blank=True, max_length=180)),
                ("voucher_bedrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("desired_move_in", models.DateField(blank=True, null=True)),
                ("desired_bedrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_rent", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("showing_at", models.DateTimeField(blank=True, null=True)),
                ("application_sent_at", models.DateTimeField(blank=True, null=True)),
                ("application_received_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_unit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="prospects", to="pm_workspace.pmunit")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_pm_prospects", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prospects", to="pm_workspace.pmworkspace")),
            ],
            options={"ordering": ["-updated_at", "-id"]},
        ),
        migrations.CreateModel(
            name="PMLease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("term", models.CharField(choices=[("MONTH_TO_MONTH", "Month to month"), ("SIX_MONTH", "6 month"), ("TWELVE_MONTH", "12 month"), ("CUSTOM", "Custom")], default="TWELVE_MONTH", max_length=24)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("converts_to_month_to_month", models.BooleanField(default=True)),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=12)),
                ("security_deposit", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("section8", models.BooleanField(default=False)),
                ("housing_authority", models.CharField(blank=True, max_length=180)),
                ("tenant_portion", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("assistance_portion", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("status", models.CharField(default="DRAFT", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leases", to="pm_workspace.pmtenant")),
                ("unit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="leases", to="pm_workspace.pmunit")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leases", to="pm_workspace.pmworkspace")),
            ],
            options={"ordering": ["-start_date", "-id"]},
        ),
        migrations.CreateModel(
            name="PMDocumentPacket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("packet_type", models.CharField(default="LEASE", max_length=80)),
                ("state_code", models.CharField(blank=True, max_length=2)),
                ("housing_authority", models.CharField(blank=True, max_length=180)),
                ("template_name", models.CharField(max_length=180)),
                ("template_version", models.CharField(blank=True, max_length=80)),
                ("source_url", models.URLField(blank=True)),
                ("field_data", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SENT", "Sent"), ("PARTIALLY_SIGNED", "Partially signed"), ("COMPLETED", "Completed"), ("VOID", "Void")], default="DRAFT", max_length=24)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lease", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="document_packets", to="pm_workspace.pmlease")),
                ("prospect", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="document_packets", to="pm_workspace.pmprospect")),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="document_packets", to="pm_workspace.pmtenant")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="document_packets", to="pm_workspace.pmworkspace")),
            ],
            options={"ordering": ["-updated_at", "-id"]},
        ),
        migrations.CreateModel(
            name="PMLedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_date", models.DateField(default=django.utils.timezone.localdate)),
                ("entry_type", models.CharField(choices=[("CHARGE", "Charge"), ("PAYMENT", "Payment"), ("CREDIT", "Credit"), ("ADJUSTMENT", "Adjustment")], max_length=16)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("category", models.CharField(default="RENT", max_length=80)),
                ("payment_method", models.CharField(blank=True, choices=[("CASH", "Cash"), ("CHECK", "Check"), ("ACH", "ACH"), ("CARD", "Card"), ("MONEY_ORDER", "Money order"), ("HOUSING_AUTHORITY", "Housing authority"), ("OTHER", "Other")], max_length=24)),
                ("reference", models.CharField(blank=True, max_length=180)),
                ("memo", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_pm_ledger_entries", to=settings.AUTH_USER_MODEL)),
                ("lease", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ledger_entries", to="pm_workspace.pmlease")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ledger_entries", to="pm_workspace.pmtenant")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ledger_entries", to="pm_workspace.pmworkspace")),
            ],
            options={"ordering": ["-entry_date", "-id"]},
        ),
        migrations.AddConstraint(model_name="pmunit", constraint=models.UniqueConstraint(fields=("property", "label"), name="uniq_pm_property_unit_label")),
        migrations.AddIndex(model_name="pmprospect", index=models.Index(fields=["workspace", "stage"], name="pm_workspac_workspa_58f003_idx")),
        migrations.AddIndex(model_name="pmledgerentry", index=models.Index(fields=["workspace", "tenant", "entry_date"], name="pm_workspac_workspa_d3c9ce_idx")),
    ]
