# Generated by SyncWorks controlled migration audit on 2026-07-13
from __future__ import annotations

import platform_growth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_growth", "0003_platform_automation_engine_foundation"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name="growthcontentqueueitem",
                    new_name="platform_gr_status_3dfed5_idx",
                    old_name="platform_gro_status_725f79_idx",
                ),
                migrations.RenameIndex(
                    model_name="growthoauthstate",
                    new_name="platform_gr_provide_747e46_idx",
                    old_name="platform_gro_provide_2664aa_idx",
                ),
                migrations.RenameIndex(
                    model_name="growthoauthstate",
                    new_name="platform_gr_expires_fb98ba_idx",
                    old_name="platform_gro_expires_0d53c0_idx",
                ),
                migrations.RenameIndex(
                    model_name="growthscheduledpostjob",
                    new_name="platform_gr_status_1aa7f6_idx",
                    old_name="platform_gro_status_3a74f0_idx",
                ),
                migrations.RenameIndex(
                    model_name="platformactivationevent",
                    new_name="platform_gr_source_f183c4_idx",
                    old_name="platform_gro_source_74f5c3_idx",
                ),
                migrations.RenameIndex(
                    model_name="platformactivationevent",
                    new_name="platform_gr_externa_787822_idx",
                    old_name="platform_gro_externa_589f45_idx",
                ),
                migrations.RenameIndex(
                    model_name="platformconversation",
                    new_name="platform_gr_channel_4b7cea_idx",
                    old_name="platform_gro_channel_1335fb_idx",
                ),
                migrations.RenameIndex(
                    model_name="platformconversation",
                    new_name="platform_gr_status_fc0c56_idx",
                    old_name="platform_gro_status_6faf49_idx",
                ),
                migrations.RenameIndex(
                    model_name="platformlead",
                    new_name="platform_gr_source_106436_idx",
                    old_name="platform_gro_source_8dafc8_idx",
                ),
                migrations.RenameIndex(
                    model_name="platformlead",
                    new_name="platform_gr_status_2b0088_idx",
                    old_name="platform_gro_status_2f87e2_idx",
                ),
                migrations.RenameIndex(
                    model_name="platformmessage",
                    new_name="platform_gr_externa_1247c5_idx",
                    old_name="platform_gro_externa_3e8ba1_idx",
                ),
                migrations.RenameIndex(
                    model_name="platformmessage",
                    new_name="platform_gr_sent_at_b1c604_idx",
                    old_name="platform_gro_sent_at_2e8ef8_idx",
                ),
                migrations.AlterField(
                    model_name="growthoauthstate",
                    name="expires_at",
                    field=models.DateTimeField(default=platform_growth.models.default_oauth_state_expiry),
                ),
            ],
        ),
    ]