# Generated by SyncWorks controlled migration audit on 2026-07-13
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_affiliates", "0002_agreement_templates"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name="affiliateagreementacceptance",
                    new_name="platform_af_affilia_1328c4_idx",
                    old_name="platform_af_affilia_9122ae_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliateagreementacceptance",
                    new_name="platform_af_agreeme_ab2a24_idx",
                    old_name="platform_af_agreeme_6317c2_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliateagreementtemplate",
                    new_name="platform_af_version_af8e95_idx",
                    old_name="platform_af_version_9e6798_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliateagreementtemplate",
                    new_name="platform_af_is_acti_de8fc3_idx",
                    old_name="platform_af_is_acti_4262a5_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliateauditlog",
                    new_name="platform_af_action_bff5a6_idx",
                    old_name="platform_af_action_05090d_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliateauditlog",
                    new_name="platform_af_affilia_b794cc_idx",
                    old_name="platform_af_affilia_4c7b0e_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliateauditlog",
                    new_name="platform_af_busines_9aa09b_idx",
                    old_name="platform_af_busines_8c3ccf_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliatecommissionledger",
                    new_name="platform_af_affilia_3b7b5c_idx",
                    old_name="platform_af_affilia_e52213_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliatecommissionledger",
                    new_name="platform_af_busines_80c98f_idx",
                    old_name="platform_af_busines_077973_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliatecommissionledger",
                    new_name="platform_af_revenue_64a204_idx",
                    old_name="platform_af_revenue_70b48d_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliatecommissionledger",
                    new_name="platform_af_source__724ea7_idx",
                    old_name="platform_af_source__87317b_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliatepartner",
                    new_name="platform_af_code_ea0007_idx",
                    old_name="platform_af_code_823f90_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliatepartner",
                    new_name="platform_af_status_6c7165_idx",
                    old_name="platform_af_status_fa27e8_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliatepartner",
                    new_name="platform_af_email_c1a26c_idx",
                    old_name="platform_af_email_a5ef01_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliatepayoutbatch",
                    new_name="platform_af_affilia_9269ee_idx",
                    old_name="platform_af_affilia_b1f865_idx",
                ),
                migrations.RenameIndex(
                    model_name="affiliatepayoutbatch",
                    new_name="platform_af_period__372e43_idx",
                    old_name="platform_af_period__440c21_idx",
                ),
                migrations.RenameIndex(
                    model_name="referralattribution",
                    new_name="platform_af_referra_2e9ee8_idx",
                    old_name="platform_af_referra_68fafa_idx",
                ),
                migrations.RenameIndex(
                    model_name="referralattribution",
                    new_name="platform_af_affilia_49e470_idx",
                    old_name="platform_af_affilia_f8fc68_idx",
                ),
                migrations.RenameIndex(
                    model_name="referralattribution",
                    new_name="platform_af_effecti_3bfc74_idx",
                    old_name="platform_af_effect_4d7101_idx",
                ),
                migrations.RenameIndex(
                    model_name="referralclick",
                    new_name="platform_af_code_b7e95b_idx",
                    old_name="platform_af_code_8d881f_idx",
                ),
                migrations.RenameIndex(
                    model_name="referralclick",
                    new_name="platform_af_created_407594_idx",
                    old_name="platform_af_created_85e483_idx",
                ),
                migrations.AlterField(
                    model_name="affiliatecommissionledger",
                    name="revenue_source",
                    field=models.CharField(
                        choices=[
                            ("PLATFORM_FEE", "Platform Fee"),
                            ("SBO_SUBSCRIPTION", "SBO Subscription"),
                            ("GROWTH_OS_SUBSCRIPTION", "Growth OS Subscription"),
                            ("HEALTH_SUBSCRIPTION", "Health Subscription"),
                            ("HEALTH_AI_SUBSCRIPTION", "Health AI Subscription"),
                            ("OTHER_SYNCWORKS_REVENUE", "Other SyncWorks Revenue"),
                        ],
                        default="PLATFORM_FEE",
                        max_length=40,
                    ),
                ),
            ],
        ),
    ]