# Generated by Django 5.2.9 on 2026-01-03 20:14

import django.db.models.deletion
import user_accounts.models.invites
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitecode',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='businesscategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='businesscategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='businesscategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='invitecode',
            name='data',
        ),
        migrations.RemoveField(
            model_name='invitecode',
            name='purpose',
        ),
        migrations.AddField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='can_assign_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='can_close_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='can_create_tickets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='can_manage_categories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='can_manage_connections',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='can_manage_invoices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='can_manage_properties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='can_manage_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='can_manage_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='can_manage_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='can_view_financials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='user_accounts.business'),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='can_assign_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='can_close_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='can_create_tickets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='can_manage_categories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='can_manage_connections',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='can_manage_invoices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='can_manage_properties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='can_manage_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='can_manage_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='can_manage_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='can_view_financials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('DISPATCH', 'Dispatch'), ('TECH', 'Technician'), ('ACCOUNTING', 'Accounting')], default='TECH', max_length=20),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_accounts.businesscategory'),
        ),
        migrations.AlterField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='businessmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='businessmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('DISPATCH', 'Dispatch'), ('TECH', 'Technician'), ('ACCOUNTING', 'Accounting')], default='TECH', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(default=user_accounts.models.invites.generate_code, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='expires_at',
            field=models.DateTimeField(default=user_accounts.models.invites.default_expires_at),
        ),
    ]
