# Generated by Django 5.2.9 on 2026-01-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_alter_invitecode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, help_text='SyncWorks internal platform admin (God Mode)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SBO', 'Small Business Owner'), ('SUB', 'Subcontractor'), ('EMPLOYEE', 'Employee')], default='CUSTOMER', max_length=20),
        ),
    ]
