# Generated by Django 5.2.9 on 2026-01-05 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_user_is_platform_admin_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=128)),
                ('stripe_default_payment_method_id', models.CharField(blank=True, default='', max_length=128)),
                ('stripe_setup_complete', models.BooleanField(default=False)),
                ('is_sbo_active', models.BooleanField(default=False)),
                ('is_pm_active', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_reason', models.CharField(blank=True, default='', max_length=255)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('grace_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_billing', to='user_accounts.business')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPlatformBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_paid_invoices_cents', models.BigIntegerField(default=0)),
                ('platform_fee_cents', models.BigIntegerField(default=0)),
                ('sbo_subscription_cents', models.BigIntegerField(default=0)),
                ('pm_subscription_cents', models.BigIntegerField(default=0)),
                ('seats_cents', models.BigIntegerField(default=0)),
                ('total_due_cents', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='DRAFT', max_length=16)),
                ('stripe_invoice_id', models.CharField(blank=True, default='', max_length=128)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=128)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_bills', to='user_accounts.business')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='user_accounts.platformbillingprofile')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('business', 'period_start')},
            },
        ),
    ]
