# Generated by Django 5.2.9 on 2026-01-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0005_platformnewsitem_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformnewsitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newsreel/'),
        ),
        migrations.AlterField(
            model_name='platformnewsitem',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='platformnewsitem',
            name='link_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
