# Generated by Django 5.2.9 on 2026-01-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0006_platformnewsitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformnewsitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='platformnewsitem',
            name='target_scope',
            field=models.CharField(choices=[('ALL', 'All'), ('CUSTOMER', 'Customers'), ('SBO', 'SBOs'), ('PM', 'Property Managers')], default='ALL', max_length=16),
        ),
        migrations.AddField(
            model_name='platformnewsitem',
            name='target_zip_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='platformnewsitem',
            name='link_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
