# Generated by Django 5.2.9 on 2026-01-08 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0008_rename_assigned_to_ticket_assigned_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user_accounts.servicecategory'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='business',
            name='services_offered',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='user_accounts.servicecategory'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='key',
            field=models.SlugField(max_length=140, unique=True),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['key'], name='user_accoun_key_b9bc4d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['parent'], name='user_accoun_parent__0c1b80_idx'),
        ),
    ]
