# Generated by Django 5.2.9 on 2026-01-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0009_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='service_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_radius_miles',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_zip',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
