# Generated by Django 5.2.9 on 2026-01-09 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0010_ticket_service_address_ticket_service_radius_miles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='business',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='city',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='desired_date',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='max_budget',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='state',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_sbo_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('MATCHED', 'Matched'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='service_zip',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
