# Generated by Django 5.2.9 on 2026-01-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0011_remove_servicerequest_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='billing_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='billing_exempt_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='billing_exempt_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
