# Generated by Django 5.2.9 on 2026-01-11 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0012_business_billing_exempt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyplatformbill',
            options={'ordering': ('-period_start',)},
        ),
        migrations.AlterModelOptions(
            name='platformbillingprofile',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='monthlyplatformbill',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='platformbillingprofile',
            name='is_pm_active',
        ),
        migrations.RemoveField(
            model_name='platformbillingprofile',
            name='is_sbo_active',
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='subscription_cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='subscription_current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='subscription_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='monthlyplatformbill',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_accounts.business'),
        ),
        migrations.AlterField(
            model_name='monthlyplatformbill',
            name='gross_paid_invoices_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyplatformbill',
            name='platform_fee_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyplatformbill',
            name='pm_subscription_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyplatformbill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_accounts.platformbillingprofile'),
        ),
        migrations.AlterField(
            model_name='monthlyplatformbill',
            name='sbo_subscription_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyplatformbill',
            name='seats_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlyplatformbill',
            name='status',
            field=models.CharField(default='DRAFT', max_length=16),
        ),
        migrations.AlterField(
            model_name='monthlyplatformbill',
            name='total_due_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformbillingprofile',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='user_accounts.business'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_exempt', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True)),
                ('redemption_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to='user_accounts.business')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='user_accounts.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-redeemed_at',),
                'unique_together': {('promo', 'business')},
            },
        ),
    ]
