# Generated by Django 5.2.9 on 2026-01-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0013_alter_monthlyplatformbill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='business_logos/'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
