# Generated by Django 4.2.14 on 2026-01-15 03:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0014_business_business_email_business_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDailyKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, unique=True)),
                ('signups', models.IntegerField(default=0)),
                ('businesses_created', models.IntegerField(default=0)),
                ('active_businesses_30d', models.IntegerField(default=0)),
                ('marketplace_tickets_created', models.IntegerField(default=0)),
                ('marketplace_tickets_accepted', models.IntegerField(default=0)),
                ('marketplace_fill_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('tickets_created', models.IntegerField(default=0)),
                ('tickets_completed', models.IntegerField(default=0)),
                ('tickets_cancelled', models.IntegerField(default=0)),
                ('open_backlog', models.IntegerField(default=0)),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('platform_fee_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('platform_fee_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_gmv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='business',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='CARD', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='platform_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='platform_fee_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='platform_fee_collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='platform_fee_rate_bps',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='awaiting_approval_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='en_route_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='on_site_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('SCHEDULED', 'Scheduled'), ('EN_ROUTE', 'En Route'), ('ON_SITE', 'On Site'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('COMPLETED', 'Completed'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='NEW', max_length=30),
        ),
        migrations.CreateModel(
            name='MarketplaceCellDailyKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('category_id', models.IntegerField(db_index=True)),
                ('zip_prefix', models.CharField(db_index=True, max_length=5)),
                ('tickets_created', models.IntegerField(default=0)),
                ('tickets_accepted', models.IntegerField(default=0)),
                ('fill_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['day', 'category_id'], name='user_accoun_day_836e22_idx'), models.Index(fields=['day', 'zip_prefix'], name='user_accoun_day_2c83c3_idx')],
                'unique_together': {('day', 'category_id', 'zip_prefix')},
            },
        ),
        migrations.CreateModel(
            name='BusinessDailyKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('business_id', models.IntegerField(db_index=True)),
                ('tickets_created', models.IntegerField(default=0)),
                ('tickets_assigned', models.IntegerField(default=0)),
                ('tickets_accepted', models.IntegerField(default=0)),
                ('tickets_completed', models.IntegerField(default=0)),
                ('tickets_cancelled', models.IntegerField(default=0)),
                ('open_backlog', models.IntegerField(default=0)),
                ('gmv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_gmv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('platform_fee_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('platform_fee_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['business_id', 'day'], name='user_accoun_busines_2cdb63_idx')],
                'unique_together': {('day', 'business_id')},
            },
        ),
        migrations.CreateModel(
            name='TicketViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CUSTOMER_VIEWED', 'Customer Viewed'), ('BUSINESS_VIEWED', 'Business Viewed'), ('BUSINESS_DECLINED', 'Business Declined')], max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_view_events', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_view_events', to='user_accounts.business')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='user_accounts.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket', 'event_type', '-created_at'], name='user_accoun_ticket__dc4886_idx'), models.Index(fields=['ticket', 'business', 'event_type', '-created_at'], name='user_accoun_ticket__d6009e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('template_type', models.CharField(choices=[('GENERAL', 'General'), ('QUOTE', 'Quote'), ('INVOICE', 'Invoice'), ('WORK_ORDER', 'Work Order')], default='GENERAL', max_length=30)),
                ('body', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='user_accounts.business')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'unique_together': {('business', 'name')},
            },
        ),
    ]
