# Generated by Django 4.2.14 on 2026-01-15 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0015_platformdailykpi_remove_invoice_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_zip', models.CharField(blank=True, default='', max_length=10)),
                ('default_address', models.CharField(blank=True, default='', max_length=255)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=False)),
                ('notify_push', models.BooleanField(default=True)),
                ('preferred_calendar_provider', models.CharField(choices=[('NONE', 'None'), ('GOOGLE', 'Google'), ('OUTLOOK', 'Outlook'), ('APPLE', 'Apple')], default='NONE', max_length=20)),
                ('calendar_sync_enabled', models.BooleanField(default=False)),
                ('health_fitness_enabled', models.BooleanField(default=False)),
                ('finance_tools_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('calendar_id', models.CharField(blank=True, default='', max_length=128)),
                ('external_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ticket_id', 'provider', 'external_event_id')},
            },
        ),
        migrations.CreateModel(
            name='CalendarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GOOGLE', 'Google'), ('OUTLOOK', 'Outlook')], max_length=20)),
                ('provider_account_id', models.CharField(blank=True, default='', max_length=128)),
                ('provider_email', models.CharField(blank=True, default='', max_length=255)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('calendar_id', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'provider', 'provider_account_id')},
            },
        ),
    ]
