# Generated by Django 4.2.14 on 2026-01-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0016_customersettings_ticketcalendarevent_calendaraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='finance_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='finance_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='finance_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='fitness_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='health_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='health_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
