# Generated by Django 4.2.14 on 2026-01-17 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0017_customersettings_finance_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('BROADCAST', 'Broadcast'), ('TICKET', 'Ticket'), ('BILLING', 'Billing'), ('MESSAGE', 'Message'), ('REMINDER', 'Reminder'), ('PROMO', 'Promo')], default='SYSTEM', max_length=32),
        ),
        migrations.CreateModel(
            name='FinanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_accoun_user_id_e1bdae_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETE', 'Complete'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('outcome_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_accoun_user_id_011c6b_idx'), models.Index(fields=['user', 'status'], name='user_accoun_user_id_9617e6_idx')],
            },
        ),
    ]
