# Generated by Django 4.2.14 on 2026-01-18 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0019_favoritebusiness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketquote',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketquote',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_quotes_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketquote',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketquote',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_quotes_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketquote',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketquote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('SCHEDULED', 'Scheduled'), ('EN_ROUTE', 'En Route'), ('ON_SITE', 'On Site'), ('IN_PROGRESS', 'In Progress'), ('NEEDS_QUOTE', 'Needs Quote'), ('QUOTED', 'Quote Sent'), ('QUOTE_REJECTED', 'Quote Rejected'), ('APPROVED', 'Quote Approved'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('COMPLETED', 'Completed'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='NEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticketviewevent',
            name='event_type',
            field=models.CharField(choices=[('CUSTOMER_VIEWED', 'Customer Viewed'), ('BUSINESS_VIEWED', 'Business Viewed'), ('BUSINESS_DECLINED', 'Business Declined'), ('DECLINED_MARKETPLACE', 'Declined Marketplace')], max_length=40),
        ),
    ]
