# Generated by Django 4.2.14 on 2026-01-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0020_ticketquote_approved_at_ticketquote_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/profile_photos/'),
        ),
    ]
