# Generated by Django 4.2.14 on 2026-01-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0021_customersettings_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='preferred_contact_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=10),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='prefix',
            field=models.CharField(choices=[('NONE', '—'), ('MR', 'Mr.'), ('MS', 'Ms.'), ('MRS', 'Mrs.'), ('MX', 'Mx.'), ('DR', 'Dr.')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='stripe_payment_method_brand',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='stripe_payment_method_exp_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='stripe_payment_method_exp_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='stripe_payment_method_last4',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
