# Generated by Django 4.2.14 on 2026-01-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0022_customersettings_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='business',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='stripe_onboarding_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
