# Generated by Django 4.2.14 on 2026-01-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0023_business_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='business',
            name='stripe_charges_enabled',
        ),
        migrations.RemoveField(
            model_name='business',
            name='stripe_onboarding_completed',
        ),
        migrations.RemoveField(
            model_name='business',
            name='stripe_onboarding_last_checked_at',
        ),
        migrations.RemoveField(
            model_name='business',
            name='stripe_payouts_enabled',
        ),
        migrations.AddField(
            model_name='business',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, default='', help_text='Stripe Connect Express account ID (acct_...)', max_length=255),
        ),
    ]
