# Generated by Django 4.2.14 on 2026-01-20 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0024_remove_business_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConnectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges_enabled', models.BooleanField(default=False)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('details_submitted', models.BooleanField(default=False)),
                ('requirements_due', models.JSONField(blank=True, default=dict)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_connect', to='user_accounts.business')),
            ],
        ),
    ]
