# Generated by Django 5.2.9 on 2026-01-23 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0025_stripeconnectprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zip', models.CharField(blank=True, default='', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WATCH', 'Watch'), ('AT_RISK', 'At Risk')], default='HEALTHY', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_properties', to='user_accounts.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='user_accoun_busines_274a94_idx'), models.Index(fields=['business', 'status'], name='user_accoun_busines_e36475_idx'), models.Index(fields=['business', 'name'], name='user_accoun_busines_aca7a8_idx')],
            },
        ),
    ]
