# Generated by Django 5.2.9 on 2026-01-23 19:45

import django.db.models.deletion
import user_accounts.models.pm_invite
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0026_pmproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Unit label like 101, A, 2B', max_length=60)),
                ('beds', models.PositiveSmallIntegerField(default=0)),
                ('baths', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance / Rehab')], default='VACANT', max_length=16)),
                ('section8_eligible', models.BooleanField(default=False)),
                ('section8_active', models.BooleanField(default=False)),
                ('market_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_units', to='user_accounts.business')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='user_accounts.pmproperty')),
            ],
            options={
                'ordering': ['property_id', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PMTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('APPLICANT', 'Applicant'), ('TENANT', 'Tenant'), ('FORMER', 'Former')], default='PROSPECT', max_length=16)),
                ('section8', models.BooleanField(default=False)),
                ('voucher_id', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_tenants', to='user_accounts.business')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='user_accounts.pmproperty')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='user_accounts.pmunit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PMInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING', max_length=16)),
                ('expires_at', models.DateTimeField(default=user_accounts.models.pm_invite._default_expires)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_invites', to='user_accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_invites_created', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='user_accounts.pmunit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pmunit',
            index=models.Index(fields=['business', 'property'], name='user_accoun_busines_78e502_idx'),
        ),
        migrations.AddIndex(
            model_name='pmunit',
            index=models.Index(fields=['business', 'status'], name='user_accoun_busines_8f1374_idx'),
        ),
        migrations.AddIndex(
            model_name='pmunit',
            index=models.Index(fields=['business', 'label'], name='user_accoun_busines_5bac28_idx'),
        ),
        migrations.AddIndex(
            model_name='pmtenant',
            index=models.Index(fields=['business', 'status'], name='user_accoun_busines_c2a408_idx'),
        ),
        migrations.AddIndex(
            model_name='pmtenant',
            index=models.Index(fields=['business', 'email'], name='user_accoun_busines_075db2_idx'),
        ),
        migrations.AddIndex(
            model_name='pmtenant',
            index=models.Index(fields=['business', 'phone'], name='user_accoun_busines_2b50cc_idx'),
        ),
        migrations.AddIndex(
            model_name='pminvite',
            index=models.Index(fields=['business', 'status'], name='user_accoun_busines_09b4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='pminvite',
            index=models.Index(fields=['business', 'email'], name='user_accoun_busines_b28d40_idx'),
        ),
    ]
