# Generated by Django 5.2.9 on 2026-01-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0027_pmunit_pmtenant_pminvite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmproperty',
            name='property_type',
            field=models.CharField(choices=[('HOME', 'Home / Single Family'), ('APARTMENT', 'Apartment Building'), ('MULTI_FAMILY', 'Multi-Family (2–4)'), ('CONDO', 'Condo'), ('COMMERCIAL', 'Commercial'), ('OTHER', 'Other')], default='HOME', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pmproperty',
            index=models.Index(fields=['business', 'property_type'], name='user_accoun_busines_35f104_idx'),
        ),
    ]
