# Generated by Django 5.2.9 on 2026-01-25 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0028_pmproperty_property_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('GENERAL', 'General'), ('LEASE', 'Lease'), ('PM_AGREEMENT', 'PM Agreement'), ('APPLICATION', 'Application'), ('SECTION8', 'Section 8'), ('INSPECTION', 'Inspection'), ('NOTICE', 'Notice'), ('RECEIPT', 'Receipt')], default='GENERAL', max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('private', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='pm/documents/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_documents', to='user_accounts.business')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user_accounts.pmproperty')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='user_accounts.pmtenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='user_accounts.pmunit')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['business', 'property', 'doc_type'], name='user_accoun_busines_c66f23_idx'), models.Index(fields=['business', 'unit'], name='user_accoun_busines_e283f0_idx'), models.Index(fields=['business', 'tenant'], name='user_accoun_busines_f13f66_idx')],
            },
        ),
    ]
