# Generated by Django 5.2.9 on 2026-01-27 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0029_pmdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMSection8Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending / Onboarding'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('housing_authority_name', models.CharField(blank=True, default='', max_length=200)),
                ('housing_authority_phone', models.CharField(blank=True, default='', max_length=40)),
                ('housing_authority_email', models.EmailField(blank=True, default='', max_length=254)),
                ('caseworker_name', models.CharField(blank=True, default='', max_length=200)),
                ('caseworker_phone', models.CharField(blank=True, default='', max_length=40)),
                ('caseworker_email', models.EmailField(blank=True, default='', max_length=254)),
                ('voucher_number', models.CharField(blank=True, default='', max_length=80)),
                ('hap_contract_number', models.CharField(blank=True, default='', max_length=80)),
                ('hap_start_date', models.DateField(blank=True, null=True)),
                ('hap_end_date', models.DateField(blank=True, null=True)),
                ('recert_due_date', models.DateField(blank=True, null=True)),
                ('recert_submitted_date', models.DateField(blank=True, null=True)),
                ('recert_approved_date', models.DateField(blank=True, null=True)),
                ('inspection_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SCHEDULED', 'Scheduled'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('REINSPECTION', 'Reinspection Needed')], default='UNKNOWN', max_length=20)),
                ('inspection_scheduled_date', models.DateField(blank=True, null=True)),
                ('inspection_completed_date', models.DateField(blank=True, null=True)),
                ('inspection_fail_reasons', models.TextField(blank=True, default='')),
                ('contract_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tenant_portion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subsidy_portion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_section8_cases', to='user_accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_section8_cases', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section8_cases', to='user_accounts.pmproperty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section8_cases', to='user_accounts.pmtenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section8_cases', to='user_accounts.pmunit')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'status'], name='user_accoun_busines_7815ad_idx'), models.Index(fields=['business', 'recert_due_date'], name='user_accoun_busines_6fa498_idx'), models.Index(fields=['business', 'inspection_status'], name='user_accoun_busines_13089a_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'tenant', 'unit'), name='uniq_section8_case_tenant_unit_per_biz')],
            },
        ),
    ]
