# Generated by Django 5.2.9 on 2026-01-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0030_pmsection8case'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsection8case',
            name='packet_items',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pmsection8case',
            name='packet_last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmsection8case',
            name='packet_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='pmsection8case',
            index=models.Index(fields=['business', 'packet_ready'], name='user_accoun_busines_1d433a_idx'),
        ),
    ]
