# Generated by Django 5.2.9 on 2026-02-01 20:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0031_pmsection8case_packet_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMBillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('rent_due_day', models.PositiveSmallIntegerField(default=1)),
                ('grace_days', models.PositiveSmallIntegerField(default=5)),
                ('late_fee_enabled', models.BooleanField(default=True)),
                ('late_fee_type', models.CharField(choices=[('FLAT', 'Flat'), ('PCT', 'Percent')], default='FLAT', max_length=16)),
                ('late_fee_flat_amount', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('late_fee_percent', models.DecimalField(decimal_places=3, default=Decimal('0.050'), max_digits=6)),
                ('auto_email_enabled', models.BooleanField(default=True)),
                ('email_send_on_due', models.BooleanField(default=True)),
                ('email_send_on_past_due', models.BooleanField(default=True)),
                ('email_send_on_late_fee', models.BooleanField(default=True)),
                ('remind_days_before_due', models.PositiveSmallIntegerField(default=3)),
                ('remind_days_after_due', models.PositiveSmallIntegerField(default=2)),
                ('from_name', models.CharField(blank=True, default='', max_length=120)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PM Billing Settings',
                'verbose_name_plural': 'PM Billing Settings',
            },
        ),
        migrations.CreateModel(
            name='PMRentCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.PositiveIntegerField(db_index=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('DUE', 'Due'), ('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('VOID', 'Voided')], db_index=True, default='DUE', max_length=12)),
                ('late_fee_assessed', models.BooleanField(default=False)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('late_fee_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('stripe_checkout_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_payment_url', models.URLField(blank=True, default='')),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_past_due_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_late_fee_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_charges', to='user_accounts.pmproperty')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_charges', to='user_accounts.pmtenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_charges', to='user_accounts.pmunit')),
            ],
            options={
                'ordering': ['-due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PMRentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card'), ('STRIPE', 'Stripe'), ('ACH', 'ACH'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='user_accounts.pmrentcharge')),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='pmrentcharge',
            index=models.Index(fields=['business_id', 'due_date'], name='user_accoun_busines_441d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='pmrentcharge',
            index=models.Index(fields=['business_id', 'status'], name='user_accoun_busines_d0b9f0_idx'),
        ),
    ]
