# Generated by Django 4.2.14 on 2026-02-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0032_pmbillingsettings_pmrentcharge_pmrentpayment_and_more'),
    ]

    operations = [
    ]
