# Generated by Django 5.2.9 on 2026-02-10 03:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0033_add_stripe_event_id_to_pmrentpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMRentPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='pmrentcharge',
            options={'ordering': ['due_date', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='pmrentcharge',
            name='user_accoun_busines_441d6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='pmrentcharge',
            name='user_accoun_busines_d0b9f0_idx',
        ),
        migrations.RemoveField(
            model_name='pmrentcharge',
            name='balance_due',
        ),
        migrations.RemoveField(
            model_name='pmrentcharge',
            name='last_late_fee_sent_at',
        ),
        migrations.RemoveField(
            model_name='pmrentcharge',
            name='last_past_due_sent_at',
        ),
        migrations.RemoveField(
            model_name='pmrentcharge',
            name='last_reminder_sent_at',
        ),
        migrations.RemoveField(
            model_name='pmrentcharge',
            name='late_fee_amount',
        ),
        migrations.RemoveField(
            model_name='pmrentcharge',
            name='late_fee_assessed',
        ),
        migrations.RemoveField(
            model_name='pmrentcharge',
            name='late_fee_assessed_at',
        ),
        migrations.RemoveField(
            model_name='pmrentcharge',
            name='paid_total',
        ),
        migrations.RemoveField(
            model_name='pmrentcharge',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='pmrentcharge',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='pmrentcharge',
            name='stripe_checkout_session_id',
        ),
        migrations.RemoveField(
            model_name='pmrentcharge',
            name='stripe_payment_url',
        ),
        migrations.RemoveField(
            model_name='pmrentpayment',
            name='stripe_event_id',
        ),
        migrations.RemoveField(
            model_name='pmrentpayment',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='pmrentcharge',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='pmrentcharge',
            name='charge_type',
            field=models.CharField(choices=[('RENT', 'Rent'), ('LATE_FEE', 'Late fee'), ('ADJUSTMENT', 'Adjustment'), ('CARRYOVER', 'Carryover')], db_index=True, default='RENT', max_length=20),
        ),
        migrations.AddField(
            model_name='pmrentcharge',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pmrentcharge',
            name='related_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_line_items', to='user_accounts.pmrentcharge'),
        ),
        migrations.AddField(
            model_name='pmrentcharge',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='pmrentpayment',
            name='business_id',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='pmrentpayment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rent_payments', to='user_accounts.pmtenant'),
        ),
        migrations.AlterField(
            model_name='pmrentcharge',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='pmrentcharge',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_charges', to='user_accounts.pmproperty'),
        ),
        migrations.AlterField(
            model_name='pmrentcharge',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], db_index=True, default='UNPAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='pmrentcharge',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_charges', to='user_accounts.pmtenant'),
        ),
        migrations.AlterField(
            model_name='pmrentcharge',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_charges', to='user_accounts.pmunit'),
        ),
        migrations.AlterField(
            model_name='pmrentpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='pmrentpayment',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_payments', to='user_accounts.pmrentcharge'),
        ),
        migrations.AlterField(
            model_name='pmrentpayment',
            name='method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='pmrentpayment',
            name='paid_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pmrentpayment',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='pmrentcharge',
            constraint=models.UniqueConstraint(fields=('business_id', 'unit', 'tenant', 'due_date', 'charge_type'), name='uniq_rent_charge_business_unit_tenant_due_type'),
        ),
        migrations.AddField(
            model_name='pmrentpaymentallocation',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='user_accounts.pmrentcharge'),
        ),
        migrations.AddField(
            model_name='pmrentpaymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='user_accounts.pmrentpayment'),
        ),
        migrations.AddConstraint(
            model_name='pmrentpaymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'charge'), name='uniq_payment_allocation_payment_charge'),
        ),
    ]
