# Generated by Django 5.2.9 on 2026-02-10 20:14

import django.db.models.deletion
import user_accounts.models.pm_employees
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0034_pmrentpaymentallocation_alter_pmrentcharge_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('job_title', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('ACCOUNTING', 'Accounting'), ('LEASING', 'Leasing'), ('MAINTENANCE', 'Maintenance'), ('TECHNICIAN', 'Technician'), ('VIEW_ONLY', 'View Only')], default='VIEW_ONLY', max_length=30)),
                ('can_view_financials', models.BooleanField(default=False)),
                ('can_manage_financials', models.BooleanField(default=False)),
                ('can_manage_properties', models.BooleanField(default=False)),
                ('can_manage_tenants', models.BooleanField(default=False)),
                ('can_manage_documents', models.BooleanField(default=False)),
                ('can_manage_work_orders', models.BooleanField(default=False)),
                ('can_manage_employees', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_employees', to='user_accounts.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_employee_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PMEmployeeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(default=user_accounts.models.pm_employees._default_invite_code, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(default=user_accounts.models.pm_employees._default_invite_expires_at)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_employee_invites', to='user_accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_employee_invites_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text='Optional: invite tied to a pre-created PMEmployee record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='user_accounts.pmemployee')),
            ],
        ),
        migrations.AddIndex(
            model_name='pmemployee',
            index=models.Index(fields=['business', 'email'], name='user_accoun_busines_c9303a_idx'),
        ),
        migrations.AddIndex(
            model_name='pmemployee',
            index=models.Index(fields=['business', 'is_active'], name='user_accoun_busines_b6c646_idx'),
        ),
        migrations.AddConstraint(
            model_name='pmemployee',
            constraint=models.UniqueConstraint(fields=('business', 'email'), name='uniq_pm_employee_business_email'),
        ),
        migrations.AddIndex(
            model_name='pmemployeeinvite',
            index=models.Index(fields=['business', 'email'], name='user_accoun_busines_2a13f6_idx'),
        ),
        migrations.AddIndex(
            model_name='pmemployeeinvite',
            index=models.Index(fields=['code'], name='user_accoun_code_30eedd_idx'),
        ),
    ]
