# Generated by Django 5.2.9 on 2026-02-13 02:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0035_pmemployee_pmemployeeinvite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmbillingsettings',
            name='maintenance_auto_cover_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pmbillingsettings',
            name='maintenance_auto_cover_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='pmbillingsettings',
            name='maintenance_deduct_from_rent_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pmbillingsettings',
            name='maintenance_deduct_requires_approval_over_limit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pmbillingsettings',
            name='mgmt_fee_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pmbillingsettings',
            name='mgmt_fee_flat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='pmbillingsettings',
            name='mgmt_fee_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.100'), max_digits=6),
        ),
        migrations.AddField(
            model_name='pmbillingsettings',
            name='mgmt_fee_type',
            field=models.CharField(choices=[('FLAT', 'Flat'), ('PCT', 'Percent')], default='PCT', max_length=16),
        ),
        migrations.AddField(
            model_name='pmbillingsettings',
            name='payout_auto_approve_if_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pmbillingsettings',
            name='payout_requires_manual_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PMInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=180)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('claim_code', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('claim_code_created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PMInvestorConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REVOKED', 'Revoked')], default='PENDING', max_length=16)),
                ('connect_code', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='user_accounts.pminvestor')),
            ],
            options={
                'unique_together': {('investor', 'business_id')},
            },
        ),
        migrations.CreateModel(
            name='PMPropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_properties', to='user_accounts.pminvestor')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='user_accounts.pmproperty')),
            ],
            options={
                'indexes': [models.Index(fields=['investor'], name='user_accoun_investo_b437f6_idx')],
            },
        ),
    ]
