# Generated by Django 5.2.9 on 2026-02-13 04:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0036_pmbillingsettings_maintenance_auto_cover_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMInboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(db_index=True)),
                ('sender_role', models.CharField(choices=[('PM', 'PM'), ('INVESTOR', 'Investor'), ('SYSTEM', 'System')], default='PM', max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PMInboxThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(db_index=True)),
                ('subject', models.CharField(blank=True, default='', max_length=180)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_by_pm_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_by_investor_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PMNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(db_index=True)),
                ('notif_type', models.CharField(choices=[('MESSAGE', 'Message'), ('STATEMENT', 'Statement'), ('ALERT', 'Alert'), ('SYSTEM', 'System')], default='MESSAGE', max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=180)),
                ('body', models.TextField(blank=True, default='')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PMPropertyInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(db_index=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('PARTNER', 'Partner')], default='OWNER', max_length=20)),
                ('ownership_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='pminvestor',
            name='claim_code',
        ),
        migrations.RemoveField(
            model_name='pminvestor',
            name='claim_code_created_at',
        ),
        migrations.RemoveField(
            model_name='pminvestor',
            name='claimed_at',
        ),
        migrations.RemoveField(
            model_name='pminvestor',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='pminvestor',
            name='status',
        ),
        migrations.AddField(
            model_name='pminvestor',
            name='business_id',
            field=models.IntegerField(db_index=True, default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pminvestor',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pminvestor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pminvestor',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='pminvestor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pminvestor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='pminvestor',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='pminvestor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_investor_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pminvestor',
            index=models.Index(fields=['business_id', 'email'], name='user_accoun_busines_6e41d0_idx'),
        ),
        migrations.AddIndex(
            model_name='pminvestor',
            index=models.Index(fields=['business_id', 'is_active'], name='user_accoun_busines_8ea87f_idx'),
        ),
        migrations.AddField(
            model_name='pminboxmessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_inbox_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pminboxthread',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_inbox_threads_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pminboxthread',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='user_accounts.pminvestor'),
        ),
        migrations.AddField(
            model_name='pminboxthread',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='user_accounts.pmproperty'),
        ),
        migrations.AddField(
            model_name='pminboxmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user_accounts.pminboxthread'),
        ),
        migrations.AddField(
            model_name='pmnotification',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user_accounts.pminvestor'),
        ),
        migrations.AddField(
            model_name='pmnotification',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='user_accounts.pminboxmessage'),
        ),
        migrations.AddField(
            model_name='pmnotification',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='user_accounts.pminboxthread'),
        ),
        migrations.AddField(
            model_name='pmpropertyinvestor',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_links', to='user_accounts.pminvestor'),
        ),
        migrations.AddField(
            model_name='pmpropertyinvestor',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_links', to='user_accounts.pmproperty'),
        ),
        migrations.AddIndex(
            model_name='pminboxthread',
            index=models.Index(fields=['business_id', 'investor'], name='user_accoun_busines_b5070c_idx'),
        ),
        migrations.AddIndex(
            model_name='pminboxthread',
            index=models.Index(fields=['business_id', 'property'], name='user_accoun_busines_c32454_idx'),
        ),
        migrations.AddIndex(
            model_name='pminboxthread',
            index=models.Index(fields=['business_id', 'status'], name='user_accoun_busines_af9a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='pminboxmessage',
            index=models.Index(fields=['business_id', 'thread', 'created_at'], name='user_accoun_busines_c48aca_idx'),
        ),
        migrations.AddIndex(
            model_name='pmnotification',
            index=models.Index(fields=['business_id', 'investor', 'read_at'], name='user_accoun_busines_c631d0_idx'),
        ),
        migrations.AddIndex(
            model_name='pmnotification',
            index=models.Index(fields=['business_id', 'created_at'], name='user_accoun_busines_c2a7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='pmpropertyinvestor',
            index=models.Index(fields=['business_id', 'investor'], name='user_accoun_busines_91415e_idx'),
        ),
        migrations.AddIndex(
            model_name='pmpropertyinvestor',
            index=models.Index(fields=['business_id', 'property'], name='user_accoun_busines_a16007_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pmpropertyinvestor',
            unique_together={('investor', 'property')},
        ),
    ]
