# Generated by Django 5.2.9 on 2026-02-16 19:25
from __future__ import annotations

from django.db import migrations, models


def normalize_roles_forward(apps, schema_editor):
    BusinessMember = apps.get_model("user_accounts", "BusinessMember")
    InviteCode = apps.get_model("user_accounts", "InviteCode")

    # Normalize legacy TECH -> TECHNICIAN
    BusinessMember.objects.filter(role="TECH").update(role="TECHNICIAN")
    InviteCode.objects.filter(role="TECH").update(role="TECHNICIAN")


def normalize_roles_backward(apps, schema_editor):
    # No safe reverse (we can't know which TECHNICIAN were previously TECH)
    return


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0037_pminboxmessage_pminboxthread_pmnotification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("MANAGER", "Manager"),
                    ("DISPATCH", "Dispatch"),
                    ("ACCOUNTING", "Accounting"),
                    ("TECHNICIAN", "Technician"),
                    ("TECH", "Technician (Legacy)"),
                ],
                default="TECHNICIAN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invitecode",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("MANAGER", "Manager"),
                    ("DISPATCH", "Dispatch"),
                    ("ACCOUNTING", "Accounting"),
                    ("TECHNICIAN", "Technician"),
                    ("TECH", "Technician (Legacy)"),
                ],
                default="TECHNICIAN",
                max_length=20,
            ),
        ),

        # ✅ Data cleanup so old rows stop living forever
        migrations.RunPython(normalize_roles_forward, normalize_roles_backward),
    ]
