# Generated by Django 5.2.9 on 2026-02-17 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0038_alter_businessmember_role_alter_invitecode_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='target_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_service_requests', to='user_accounts.business'),
        ),
    ]
