# Generated by Django 5.2.9 on 2026-02-17 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0040_pmworkorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmworkorder',
            name='assigned_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_workorders_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmworkorder',
            name='assignment_mode',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('TECH', 'Internal Tech'), ('MARKETPLACE', 'Marketplace')], db_index=True, default='UNASSIGNED', max_length=20),
        ),
        migrations.AddField(
            model_name='pmworkorder',
            name='marketplace_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmworkorder',
            name='marketplace_ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_workorder', to='user_accounts.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payer_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_as_payer', to='user_accounts.business'),
        ),
        migrations.AddIndex(
            model_name='pmworkorder',
            index=models.Index(fields=['business', 'assignment_mode'], name='user_accoun_busines_537eba_idx'),
        ),
    ]
