# Generated by Django 5.2.9 on 2026-02-18 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0041_pmworkorder_assigned_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmworkorder',
            name='assignment_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('TECH', 'Technician'), ('MARKETPLACE', 'Marketplace')], db_index=True, default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pmworkorder',
            name='marketplace_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_workorders', to='user_accounts.ticket'),
        ),
    ]
