# Generated by Django 5.2.9 on 2026-02-18 03:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0042_alter_pmworkorder_assignment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformbillingprofile',
            name='card_brand',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='card_exp_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='card_exp_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='card_last4',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='card_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='warned_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='warned_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='warned_30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='warned_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformbillingprofile',
            name='warned_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', max_length=32)),
                ('business_id', models.IntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('UNLOCK', 'Unlock Account'), ('BILLING', 'Billing Question'), ('BUG', 'Bug Report'), ('FEATURE', 'Feature Request'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=140)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests_handled', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='user_accoun_status_c569f4_idx'), models.Index(fields=['kind', '-created_at'], name='user_accoun_kind_3a26e0_idx'), models.Index(fields=['business_id', '-created_at'], name='user_accoun_busines_077392_idx')],
            },
        ),
    ]
