# Generated by Django 5.2.9 on 2026-02-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0044_businessaccesscontrol'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supportrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'UNLOCK'), ('status', 'OPEN')), fields=('business_id', 'requester', 'kind', 'status'), name='uniq_open_unlock_per_business_requester'),
        ),
    ]
