# Generated by Django 5.2.9 on 2026-02-22 01:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0045_supportrequest_uniq_open_unlock_per_business_requester'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('home_zip', models.CharField(blank=True, max_length=12, null=True)),
                ('radius_miles', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_mode', models.CharField(choices=[('per_seat', 'Per seat')], default='per_seat', max_length=24)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=128, null=True)),
                ('stripe_subscription_item_id', models.CharField(blank=True, max_length=128, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_pipelines_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='user_accounts.salespipeline')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=120)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('WON', 'Won'), ('LOST', 'Lost')], default='OPEN', max_length=8)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_prospects_created', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospects', to='user_accounts.prospectstage')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='user_accounts.salespipeline')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPipelineMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('AGENT', 'Agent')], default='AGENT', max_length=16)),
                ('is_active_seat', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downline_members', to='user_accounts.salespipelinemember')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='user_accounts.salespipeline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_pipeline_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesMemberEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(blank=True, default='', max_length=120)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='user_accounts.salespipelinemember')),
            ],
        ),
        migrations.CreateModel(
            name='SalesCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_calendar_events_created', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='user_accounts.prospect')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='user_accounts.salespipeline')),
                ('assigned_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events_assigned', to='user_accounts.salespipelinemember')),
            ],
            options={
                'ordering': ['start_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProspectEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='smtp', max_length=32)),
                ('status', models.CharField(blank=True, default='sent', max_length=32)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='user_accounts.prospect')),
                ('sent_by_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='user_accounts.salespipelinemember')),
            ],
        ),
        migrations.AddField(
            model_name='prospect',
            name='assigned_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prospects', to='user_accounts.salespipelinemember'),
        ),
        migrations.CreateModel(
            name='ProspectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NOTE', 'Note'), ('CALL', 'Call'), ('TEXT', 'Text'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('STATUS_CHANGE', 'Status change')], default='NOTE', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_prospect_activities', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='user_accounts.prospect')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['prospect', 'created_at'], name='user_accoun_prospec_2ad230_idx'), models.Index(fields=['type'], name='user_accoun_type_160678_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='salespipeline',
            index=models.Index(fields=['owner_user', 'is_active'], name='user_accoun_owner_u_c271be_idx'),
        ),
        migrations.AddIndex(
            model_name='salespipeline',
            index=models.Index(fields=['created_at'], name='user_accoun_created_17eba1_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectstage',
            index=models.Index(fields=['pipeline', 'order'], name='user_accoun_pipelin_155e71_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectstage',
            index=models.Index(fields=['pipeline', 'is_closed', 'is_won'], name='user_accoun_pipelin_a2b737_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prospectstage',
            unique_together={('pipeline', 'name')},
        ),
        migrations.AddIndex(
            model_name='salespipelinemember',
            index=models.Index(fields=['pipeline', 'role', 'is_active_seat'], name='user_accoun_pipelin_da4f45_idx'),
        ),
        migrations.AddIndex(
            model_name='salespipelinemember',
            index=models.Index(fields=['pipeline', 'created_at'], name='user_accoun_pipelin_ec7a13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salespipelinemember',
            unique_together={('pipeline', 'user')},
        ),
        migrations.AddIndex(
            model_name='salesmemberemailsettings',
            index=models.Index(fields=['is_enabled'], name='user_accoun_is_enab_38fde0_idx'),
        ),
        migrations.AddIndex(
            model_name='salescalendarevent',
            index=models.Index(fields=['pipeline', 'start_at'], name='user_accoun_pipelin_4de6af_idx'),
        ),
        migrations.AddIndex(
            model_name='salescalendarevent',
            index=models.Index(fields=['pipeline', 'end_at'], name='user_accoun_pipelin_928a91_idx'),
        ),
        migrations.AddIndex(
            model_name='salescalendarevent',
            index=models.Index(fields=['assigned_member', 'start_at'], name='user_accoun_assigne_d57552_idx'),
        ),
        migrations.AddIndex(
            model_name='salescalendarevent',
            index=models.Index(fields=['prospect'], name='user_accoun_prospec_2fe110_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectemaillog',
            index=models.Index(fields=['prospect', 'created_at'], name='user_accoun_prospec_23aa8a_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectemaillog',
            index=models.Index(fields=['status'], name='user_accoun_status_48b15d_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['pipeline', 'status'], name='user_accoun_pipelin_2cb3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['pipeline', 'stage'], name='user_accoun_pipelin_994744_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['pipeline', 'assigned_member'], name='user_accoun_pipelin_591c73_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['pipeline', 'created_at'], name='user_accoun_pipelin_c2b53b_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['last_activity_at'], name='user_accoun_last_ac_ab8c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['next_follow_up_at'], name='user_accoun_next_fo_d8e8fd_idx'),
        ),
    ]
