# Generated by Django 5.2.9 on 2026-02-23 01:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0046_salespipeline_prospectstage_prospect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sales/prospect_attachments/%Y/%m/')),
                ('title', models.CharField(blank=True, default='', max_length=180)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='user_accounts.prospect')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_prospect_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['prospect', 'created_at'], name='user_accoun_prospec_fa2474_idx')],
            },
        ),
    ]
