# Generated by Django 5.2.9 on 2026-02-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0047_prospectattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectactivity',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospectactivity',
            name='type',
            field=models.CharField(choices=[('NOTE', 'Note'), ('CALL', 'Call'), ('TEXT', 'Text'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('TASK', 'Task'), ('STATUS_CHANGE', 'Status change')], default='NOTE', max_length=24),
        ),
        migrations.AddIndex(
            model_name='prospectactivity',
            index=models.Index(fields=['occurred_at'], name='user_accoun_occurre_aa8e54_idx'),
        ),
    ]
