# Generated by Django 5.2.9 on 2026-02-24 02:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0050_salesos_schema_sync"),
    ]

    operations = [
        # ---------------------------------------------------------------------
        # ✅ SQLITE SAFETY FIXES (REMOVE INDEXES THAT REFERENCE FIELDS WE DROP)
        # ---------------------------------------------------------------------
        # ProspectEmailLog had indexes from earlier migrations that referenced `prospect`.
        # When SQLite rebuilds the table during RemoveField, it tries to recreate indexes
        # and crashes if any index still references the removed field.
        migrations.RemoveIndex(
            model_name="prospectemaillog",
            name="user_accoun_prospec_23aa8a_idx",
        ),
        migrations.RemoveIndex(
            model_name="prospectemaillog",
            name="user_accoun_status_48b15d_idx",
        ),

        # ProspectActivity had an index referencing `prospect` as well.
        migrations.RemoveIndex(
            model_name="prospectactivity",
            name="user_accoun_prospec_2ad230_idx",
        ),

        # ---------------------------------------------------------------------
        # Your generated operations (unchanged order except safe index removals above)
        # ---------------------------------------------------------------------
        migrations.RemoveField(
            model_name="prospectactivity",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="prospectactivity",
            name="prospect",
        ),
        migrations.RemoveField(
            model_name="prospectemaillog",
            name="prospect",
        ),
        migrations.RemoveField(
            model_name="prospectemaillog",
            name="sent_by_member",
        ),
        migrations.RemoveField(
            model_name="salesmemberemailsettings",
            name="member",
        ),
        migrations.AlterModelOptions(
            name="prospect",
            options={"ordering": ["-updated_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="prospectattachment",
            options={"ordering": ["-uploaded_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="prospectstage",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="salespipeline",
            options={"ordering": ["-updated_at", "-id"]},
        ),
        migrations.RemoveIndex(
            model_name="prospect",
            name="user_accoun_pipelin_2cb3ca_idx",
        ),
        migrations.RemoveIndex(
            model_name="prospect",
            name="user_accoun_pipelin_994744_idx",
        ),
        migrations.RemoveIndex(
            model_name="prospect",
            name="user_accoun_pipelin_591c73_idx",
        ),
        migrations.RemoveIndex(
            model_name="prospect",
            name="user_accoun_pipelin_c2b53b_idx",
        ),
        migrations.RemoveIndex(
            model_name="prospect",
            name="user_accoun_last_ac_ab8c5a_idx",
        ),
        migrations.RemoveIndex(
            model_name="prospect",
            name="user_accoun_next_fo_d8e8fd_idx",
        ),
        migrations.RemoveIndex(
            model_name="prospectattachment",
            name="user_accoun_prospec_fa2474_idx",
        ),
        migrations.RemoveIndex(
            model_name="prospectstage",
            name="user_accoun_pipelin_155e71_idx",
        ),
        migrations.RemoveIndex(
            model_name="prospectstage",
            name="user_accoun_pipelin_a2b737_idx",
        ),
        migrations.RemoveIndex(
            model_name="salespipeline",
            name="user_accoun_owner_u_c271be_idx",
        ),
        migrations.RemoveIndex(
            model_name="salespipeline",
            name="user_accoun_created_17eba1_idx",
        ),
        migrations.RemoveIndex(
            model_name="salespipelinemember",
            name="user_accoun_pipelin_da4f45_idx",
        ),
        migrations.RemoveIndex(
            model_name="salespipelinemember",
            name="user_accoun_pipelin_ec7a13_idx",
        ),
        migrations.RenameField(
            model_name="prospect",
            old_name="full_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="prospectstage",
            old_name="is_closed",
            new_name="is_lost",
        ),
        migrations.RenameField(
            model_name="prospectstage",
            old_name="order",
            new_name="sort_order",
        ),
        migrations.RenameField(
            model_name="salespipelinemember",
            old_name="is_active_seat",
            new_name="is_active",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="assigned_member",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="closed_at",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="estimated_value",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="last_activity_at",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="next_follow_up_at",
        ),
        migrations.RemoveField(
            model_name="prospect",
            name="source",
        ),
        migrations.RemoveField(
            model_name="prospectattachment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="prospectattachment",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="prospectattachment",
            name="title",
        ),
        migrations.RemoveField(
            model_name="salespipeline",
            name="billing_mode",
        ),
        migrations.RemoveField(
            model_name="salespipeline",
            name="home_zip",
        ),
        migrations.RemoveField(
            model_name="salespipeline",
            name="is_locked",
        ),
        migrations.RemoveField(
            model_name="salespipeline",
            name="owner_user",
        ),
        migrations.RemoveField(
            model_name="salespipeline",
            name="radius_miles",
        ),
        migrations.RemoveField(
            model_name="salespipeline",
            name="stripe_subscription_id",
        ),
        migrations.RemoveField(
            model_name="salespipeline",
            name="stripe_subscription_item_id",
        ),
        migrations.RemoveField(
            model_name="salespipelinemember",
            name="parent_agent",
        ),
        migrations.AddField(
            model_name="prospect",
            name="company",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="prospect",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_prospects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prospect",
            name="value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="prospectattachment",
            name="content_type",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="prospectattachment",
            name="original_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="prospectattachment",
            name="size_bytes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prospectattachment",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prospectstage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salespipeline",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_prospects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prospects",
                to="user_accounts.prospectstage",
            ),
        ),
        migrations.AlterField(
            model_name="prospect",
            name="status",
            field=models.CharField(
                choices=[("OPEN", "Open"), ("WON", "Won"), ("LOST", "Lost")],
                default="OPEN",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="prospectattachment",
            name="file",
            field=models.FileField(upload_to="sales/prospect_attachments/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="prospectattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prospect_attachments_uploaded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="prospectstage",
            name="name",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="salespipeline",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="salespipeline",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_sales_pipelines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="salespipeline",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="salespipelinemember",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="salespipelinemember",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("MANAGER", "Manager"),
                    ("AGENT", "Agent"),
                    ("VIEWER", "Viewer"),
                ],
                default="AGENT",
                max_length=16,
            ),
        ),
        migrations.DeleteModel(
            name="ProspectActivity",
        ),
        migrations.DeleteModel(
            name="ProspectEmailLog",
        ),
        migrations.DeleteModel(
            name="SalesMemberEmailSettings",
        ),
    ]