# Generated by Django 5.2.9 on 2026-02-25 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0051_remove_prospectactivity_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='assigned_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prospects', to='user_accounts.salespipelinemember'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='prospect',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='status_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='salespipeline',
            name='billing_mode',
            field=models.CharField(choices=[('per_seat', 'Per seat'), ('flat', 'Flat')], default='per_seat', max_length=32),
        ),
        migrations.AddField(
            model_name='salespipeline',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='salespipeline',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='salespipeline',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='salespipelinemember',
            name='is_active_seat',
            field=models.BooleanField(default=True),
        ),
    ]
