# Generated by Django 5.2.9 on 2026-03-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0054_ticket_cash_fields'),
        ('user_accounts', '0055_create_invoice_model'),
    ]

    operations = [
    ]
