# Generated by Django 5.2.9 on 2026-03-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0056_merge_20260228_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cash_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='cash_fee_invoiced_month',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='total_amount_cents',
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['business', 'kind', 'status'], name='user_accoun_busines_f53f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['kind', 'period_start', 'period_end'], name='user_accoun_kind_e004ab_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'status'], name='user_accoun_due_dat_385a3c_idx'),
        ),
    ]
