# Generated by Django 5.2.9 on 2026-03-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0057_remove_ticket_cash_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cash_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When SBO confirmed they collected cash (counts into cash GMV).', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cash_fee_invoiced_month',
            field=models.CharField(blank=True, default='', help_text="YYYY-MM last month this ticket's cash fee was included in.", max_length=7),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='CARD', help_text='How the job was paid. CASH triggers monthly 1% fee billing.', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_amount_cents',
            field=models.PositiveIntegerField(default=0, help_text='Total ticket/job amount in cents (used for GMV + cash billing).'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_business', 'created_at'], name='user_accoun_assigne_811e41_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_business', 'payment_method', 'cash_confirmed_at'], name='user_accoun_assigne_0caf48_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['payment_method', 'cash_confirmed_at'], name='user_accoun_payment_f98df2_idx'),
        ),
    ]
