# Generated by Django 5.2.9 on 2026-03-01 04:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0059_rebuild_invoice_table_sqlite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('VOID', 'Void')], default='OPEN', max_length=20)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_fee_invoices', to='user_accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_fee_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='user_accoun_busines_32dd3f_idx'), models.Index(fields=['period_start', 'period_end'], name='user_accoun_period__c51cd0_idx'), models.Index(fields=['due_date', 'status'], name='user_accoun_due_dat_306575_idx')],
                'constraints': [models.UniqueConstraint(fields=('business', 'period_start', 'period_end'), name='uniq_cash_fee_invoice_business_period')],
            },
        ),
    ]
