# Generated by Django 5.2.9 on 2026-03-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0064_backfill_business_card_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='background_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='business',
            name='emergency_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='expected_gross_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_bonded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_insured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_licensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
