# Generated by Django 5.2.9 on 2026-03-05 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0065_business_background_checked_business_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=128)),
                ('stripe_default_payment_method_id', models.CharField(blank=True, default='', max_length=128)),
                ('stripe_setup_complete', models.BooleanField(default=False)),
                ('card_brand', models.CharField(blank=True, default='', max_length=32)),
                ('card_last4', models.CharField(blank=True, default='', max_length=8)),
                ('card_exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card_exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_billing_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
