# Generated by Django 5.2.12 on 2026-03-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0066_userbillingprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbillingprofile',
            options={'ordering': ('-created_at',)},
        ),
    ]
