# Generated by Django 5.2.9 on 2026-03-14 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0068_fix_salespipeline_missing_stripe_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='user_accounts.ticket'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['ticket', 'status'], name='user_accoun_ticket__fc1c6a_idx'),
        ),
    ]
