# Generated by Django 5.2.9 on 2026-03-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0069_invoice_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_presence_mode',
            field=models.CharField(blank=True, choices=[('online', 'Online Business'), ('in_person', 'In Person'), ('on_site', 'On-Site Service'), ('hybrid', 'Online + On-Site')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='facebook_url',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='business',
            name='google_business_url',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram_url',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='business',
            name='is_online_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='linkedin_url',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='business',
            name='tiktok_url',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='business',
            name='youtube_url',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
    ]
