# Generated by Django 5.2.9 on 2026-03-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0070_business_business_presence_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbillingprofile',
            name='beta_access_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userbillingprofile',
            name='beta_access_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbillingprofile',
            name='beta_access_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbillingprofile',
            name='beta_billing_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbillingprofile',
            name='beta_subscriptions_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbillingprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='userbillingprofile',
            name='subscription_cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbillingprofile',
            name='subscription_current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbillingprofile',
            name='subscription_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
