# Generated by Django 5.2.9 on 2026-04-15 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0074_rebuild_invoice_table_sqlite_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["assigned_business", "archived_at"],
                name="user_accoun_assigne_bb0a1e_idx",
            ),
        ),
    ]