from decimal import Decimal
from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
import django.utils.timezone
class Migration(migrations.Migration):
    dependencies=[('user_accounts','0105_ticket_workflow_dependencies')]
    operations=[
        migrations.CreateModel(name='InventoryLocation',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=160)),('code',models.CharField(blank=True,default='',max_length=64)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(default=django.utils.timezone.now)),('business',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='inventory_locations',to='user_accounts.business'))],options={'ordering':['name','id']}),
        migrations.CreateModel(name='Vendor',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=180)),('contact_name',models.CharField(blank=True,default='',max_length=160)),('email',models.EmailField(blank=True,default='',max_length=254)),('phone',models.CharField(blank=True,default='',max_length=40)),('notes',models.TextField(blank=True,default='')),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(default=django.utils.timezone.now)),('business',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='vendors',to='user_accounts.business'))],options={'ordering':['name','id']}),
        migrations.CreateModel(name='InventoryItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=180)),('sku',models.CharField(blank=True,default='',max_length=100)),('barcode',models.CharField(blank=True,default='',max_length=160)),('unit',models.CharField(default='each',max_length=32)),('reorder_point',models.DecimalField(decimal_places=3,default=Decimal('0'),max_digits=12)),('reorder_quantity',models.DecimalField(decimal_places=3,default=Decimal('0'),max_digits=12)),('unit_cost',models.DecimalField(decimal_places=2,default=Decimal('0'),max_digits=12)),('metadata',models.JSONField(blank=True,default=dict)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(default=django.utils.timezone.now)),('updated_at',models.DateTimeField(auto_now=True)),('business',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='inventory_items',to='user_accounts.business')),('preferred_vendor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='preferred_items',to='user_accounts.vendor'))],options={'ordering':['name','id']}),
        migrations.CreateModel(name='InventoryStock',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity_on_hand',models.DecimalField(decimal_places=3,default=Decimal('0'),max_digits=14)),('quantity_reserved',models.DecimalField(decimal_places=3,default=Decimal('0'),max_digits=14)),('updated_at',models.DateTimeField(auto_now=True)),('item',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='stock_records',to='user_accounts.inventoryitem')),('location',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='stock_records',to='user_accounts.inventorylocation'))]),
        migrations.CreateModel(name='PurchaseOrder',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('po_number',models.CharField(max_length=80)),('status',models.CharField(choices=[('DRAFT','Draft'),('SUBMITTED','Submitted'),('PARTIAL','Partial'),('RECEIVED','Received'),('CANCELLED','Cancelled')],default='DRAFT',max_length=20)),('expected_at',models.DateTimeField(blank=True,null=True)),('notes',models.TextField(blank=True,default='')),('created_at',models.DateTimeField(default=django.utils.timezone.now)),('updated_at',models.DateTimeField(auto_now=True)),('business',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='purchase_orders',to='user_accounts.business')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='purchase_orders_created',to=settings.AUTH_USER_MODEL)),('vendor',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='purchase_orders',to='user_accounts.vendor'))],options={'ordering':['-created_at','-id']}),
        migrations.CreateModel(name='PurchaseOrderLine',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity_ordered',models.DecimalField(decimal_places=3,max_digits=14)),('quantity_received',models.DecimalField(decimal_places=3,default=Decimal('0'),max_digits=14)),('unit_cost',models.DecimalField(decimal_places=2,default=Decimal('0'),max_digits=12)),('note',models.CharField(blank=True,default='',max_length=255)),('item',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='purchase_order_lines',to='user_accounts.inventoryitem')),('purchase_order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='lines',to='user_accounts.purchaseorder')),('ticket',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='purchase_order_lines',to='user_accounts.ticket'))],options={'ordering':['id']}),
        migrations.CreateModel(name='PurchaseReceipt',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity_received',models.DecimalField(decimal_places=3,max_digits=14)),('received_at',models.DateTimeField(default=django.utils.timezone.now)),('note',models.CharField(blank=True,default='',max_length=255)),('line',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='receipts',to='user_accounts.purchaseorderline')),('location',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='purchase_receipts',to='user_accounts.inventorylocation')),('purchase_order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='receipts',to='user_accounts.purchaseorder')),('received_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='purchase_receipts_created',to=settings.AUTH_USER_MODEL))],options={'ordering':['-received_at','-id']}),
        migrations.CreateModel(name='StockMovement',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('movement_type',models.CharField(choices=[('RECEIVE','Receive'),('ISSUE','Issue'),('ADJUST','Adjust'),('RESERVE','Reserve'),('RELEASE','Release')],max_length=20)),('quantity',models.DecimalField(decimal_places=3,max_digits=14)),('quantity_after',models.DecimalField(decimal_places=3,max_digits=14)),('note',models.CharField(blank=True,default='',max_length=255)),('created_at',models.DateTimeField(default=django.utils.timezone.now)),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='stock_movements_created',to=settings.AUTH_USER_MODEL)),('item',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='movements',to='user_accounts.inventoryitem')),('location',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='movements',to='user_accounts.inventorylocation')),('ticket',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='stock_movements',to='user_accounts.ticket'))],options={'ordering':['-created_at','-id']}),
        migrations.AddConstraint(model_name='inventorylocation',constraint=models.UniqueConstraint(fields=('business','name'),name='ua_inv_location_unique')),
        migrations.AddConstraint(model_name='vendor',constraint=models.UniqueConstraint(fields=('business','name'),name='ua_vendor_name_unique')),
        migrations.AddConstraint(model_name='inventoryitem',constraint=models.UniqueConstraint(condition=models.Q(('sku',''),_negated=True),fields=('business','sku'),name='ua_inv_item_sku_unique')),
        migrations.AddIndex(model_name='inventoryitem',index=models.Index(fields=['business','is_active'],name='ua_inv_item_active_idx')),
        migrations.AddIndex(model_name='inventoryitem',index=models.Index(fields=['business','barcode'],name='ua_inv_item_barcode_idx')),
        migrations.AddConstraint(model_name='inventorystock',constraint=models.UniqueConstraint(fields=('item','location'),name='ua_inv_stock_unique')),
        migrations.AddConstraint(model_name='inventorystock',constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte',0)),name='ua_inv_stock_nonnegative')),
        migrations.AddConstraint(model_name='inventorystock',constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte',0)),name='ua_inv_reserved_nonnegative')),
        migrations.AddConstraint(model_name='purchaseorder',constraint=models.UniqueConstraint(fields=('business','po_number'),name='ua_po_number_unique')),
        migrations.AddConstraint(model_name='purchaseorderline',constraint=models.CheckConstraint(condition=models.Q(('quantity_ordered__gt',0)),name='ua_po_ordered_positive')),
        migrations.AddConstraint(model_name='purchaseorderline',constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gte',0)),name='ua_po_received_nonnegative')),
        migrations.AddConstraint(model_name='purchasereceipt',constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gt',0)),name='ua_receipt_positive')),
        migrations.AddIndex(model_name='stockmovement',index=models.Index(fields=['item','created_at'],name='ua_stock_item_time_idx')),
        migrations.AddIndex(model_name='stockmovement',index=models.Index(fields=['ticket','created_at'],name='ua_stock_ticket_time_idx')),
    ]
