# Generated by SyncWorks controlled migration audit on 2026-07-13
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_accounts", "0117_partner_billing_and_fee_lineage"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="businessdailykpi",
                    name="business_id",
                ),
                migrations.AddField(
                    model_name="businessdailykpi",
                    name="business",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_kpis",
                        to="user_accounts.business",
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name="businessdailykpi",
                    unique_together={("business", "day")},
                ),
                migrations.AlterModelOptions(
                    name="businessdailykpi",
                    options={"ordering": ["-day", "business_id"]},
                ),
            ],
        ),
    ]