# Generated by SyncWorks controlled migration audit on 2026-07-13
from __future__ import annotations

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _table_columns(schema_editor, table_name: str) -> set[str]:
    with schema_editor.connection.cursor() as cursor:
        try:
            description = schema_editor.connection.introspection.get_table_description(cursor, table_name)
        except Exception:
            return set()
    return {col.name for col in description}


def _q(schema_editor, name: str) -> str:
    return schema_editor.quote_name(name)


def _add_column_if_missing(schema_editor, table_name: str, column_name: str, definition: str) -> None:
    existing = _table_columns(schema_editor, table_name)
    if column_name in existing:
        return
    schema_editor.execute(
        f"ALTER TABLE {_q(schema_editor, table_name)} "
        f"ADD COLUMN {_q(schema_editor, column_name)} {definition}"
    )


def _update_if_columns_exist(schema_editor, table_name: str, assignments: list[tuple[str, str]]) -> None:
    existing = _table_columns(schema_editor, table_name)
    usable = [(target, expression) for target, expression in assignments if target in existing]
    if not usable:
        return

    set_clauses = []
    for target, expression in usable:
        set_clauses.append(f"{_q(schema_editor, target)} = {expression}")

    schema_editor.execute(
        f"UPDATE {_q(schema_editor, table_name)} SET " + ", ".join(set_clauses)
    )


def add_missing_kpi_columns(apps, schema_editor):
    vendor = schema_editor.connection.vendor

    if vendor == "postgresql":
        integer = "integer NOT NULL DEFAULT 0"
        decimal_12 = "numeric(12, 2) NOT NULL DEFAULT 0.00"
        varchar_10 = "varchar(10) NOT NULL DEFAULT ''"
        varchar_255 = "varchar(255) NOT NULL DEFAULT ''"
        datetime_nullable = "timestamp with time zone NULL"
    else:
        integer = "integer NOT NULL DEFAULT 0"
        decimal_12 = "decimal NOT NULL DEFAULT 0.00"
        varchar_10 = "varchar(10) NOT NULL DEFAULT ''"
        varchar_255 = "varchar(255) NOT NULL DEFAULT ''"
        datetime_nullable = "datetime NULL"

    # PlatformDailyKpi current model columns.
    platform_table = "user_accounts_platformdailykpi"
    for column, definition in [
        ("users_total", integer),
        ("businesses_total", integer),
        ("tickets_total", integer),
        ("tickets_new", integer),
        ("tickets_paid", integer),
        ("invoices_paid_count", integer),
        ("gmv_paid", decimal_12),
        ("platform_fees_paid", decimal_12),
        ("avg_response_time_seconds", decimal_12),
        ("updated_at", datetime_nullable),
    ]:
        _add_column_if_missing(schema_editor, platform_table, column, definition)

    platform_cols = _table_columns(schema_editor, platform_table)
    platform_assignments: list[tuple[str, str]] = []
    if "users_total" in platform_cols and "signups" in platform_cols:
        platform_assignments.append(("users_total", "COALESCE(signups, 0)"))
    if "businesses_total" in platform_cols and "businesses_created" in platform_cols:
        platform_assignments.append(("businesses_total", "COALESCE(businesses_created, 0)"))
    if "tickets_total" in platform_cols and "tickets_created" in platform_cols:
        platform_assignments.append(("tickets_total", "COALESCE(tickets_created, 0)"))
    if "tickets_new" in platform_cols and "tickets_created" in platform_cols:
        platform_assignments.append(("tickets_new", "COALESCE(tickets_created, 0)"))
    if "tickets_paid" in platform_cols:
        platform_assignments.append(("tickets_paid", "0"))
    if "gmv_paid" in platform_cols and "gmv" in platform_cols:
        platform_assignments.append(("gmv_paid", "COALESCE(gmv, 0)"))
    if "platform_fees_paid" in platform_cols and "platform_fee_collected" in platform_cols:
        platform_assignments.append(("platform_fees_paid", "COALESCE(platform_fee_collected, 0)"))
    if "invoices_paid_count" in platform_cols:
        platform_assignments.append(("invoices_paid_count", "0"))
    if "avg_response_time_seconds" in platform_cols:
        platform_assignments.append(("avg_response_time_seconds", "0"))
    if "updated_at" in platform_cols and "created_at" in platform_cols:
        platform_assignments.append(("updated_at", "created_at"))
    _update_if_columns_exist(schema_editor, platform_table, platform_assignments)

    # BusinessDailyKpi current model columns.
    business_table = "user_accounts_businessdailykpi"
    for column, definition in [
        ("tickets_total", integer),
        ("tickets_paid", integer),
        ("invoices_paid_count", integer),
        ("gmv_paid", decimal_12),
        ("platform_fees_paid", decimal_12),
        ("updated_at", datetime_nullable),
    ]:
        _add_column_if_missing(schema_editor, business_table, column, definition)

    business_cols = _table_columns(schema_editor, business_table)
    business_assignments: list[tuple[str, str]] = []
    if "tickets_total" in business_cols and "tickets_created" in business_cols:
        business_assignments.append(("tickets_total", "COALESCE(tickets_created, 0)"))
    if "tickets_paid" in business_cols:
        business_assignments.append(("tickets_paid", "0"))
    if "gmv_paid" in business_cols and "gmv" in business_cols:
        business_assignments.append(("gmv_paid", "COALESCE(gmv, 0)"))
    if "platform_fees_paid" in business_cols and "platform_fee_collected" in business_cols:
        business_assignments.append(("platform_fees_paid", "COALESCE(platform_fee_collected, 0)"))
    if "invoices_paid_count" in business_cols:
        business_assignments.append(("invoices_paid_count", "0"))
    if "updated_at" in business_cols and "created_at" in business_cols:
        business_assignments.append(("updated_at", "created_at"))
    _update_if_columns_exist(schema_editor, business_table, business_assignments)

    # MarketplaceCellDailyKpi current model columns.
    market_table = "user_accounts_marketplacecelldailykpi"
    for column, definition in [
        ("zip_code", varchar_10),
        ("category_key", varchar_255),
        ("tickets_viewed", integer),
        ("tickets_declined", integer),
        ("tickets_assigned", integer),
        ("tickets_completed", integer),
        ("updated_at", datetime_nullable),
    ]:
        _add_column_if_missing(schema_editor, market_table, column, definition)

    market_cols = _table_columns(schema_editor, market_table)
    market_assignments: list[tuple[str, str]] = []
    if "zip_code" in market_cols and "zip_prefix" in market_cols:
        market_assignments.append(("zip_code", "COALESCE(zip_prefix, '')"))
    if "category_key" in market_cols and "category_id" in market_cols:
        market_assignments.append(("category_key", "COALESCE(CAST(category_id AS varchar), '')"))
    if "tickets_assigned" in market_cols and "tickets_accepted" in market_cols:
        market_assignments.append(("tickets_assigned", "COALESCE(tickets_accepted, 0)"))
    if "tickets_viewed" in market_cols:
        market_assignments.append(("tickets_viewed", "0"))
    if "tickets_declined" in market_cols:
        market_assignments.append(("tickets_declined", "0"))
    if "tickets_completed" in market_cols:
        market_assignments.append(("tickets_completed", "0"))
    if "updated_at" in market_cols and "created_at" in market_cols:
        market_assignments.append(("updated_at", "created_at"))
    _update_if_columns_exist(schema_editor, market_table, market_assignments)


class Migration(migrations.Migration):
    dependencies = [
        ("user_accounts", "0118_businessdailykpi_state_sync"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_missing_kpi_columns, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterModelOptions(
                    name="marketplacecelldailykpi",
                    options={"ordering": ["-day", "zip_code", "category_key"]},
                ),
                migrations.RemoveIndex(
                    model_name="businessdailykpi",
                    name="user_accoun_busines_2cdb63_idx",
                ),
                migrations.RemoveIndex(
                    model_name="invoice",
                    name="user_accoun_busines_f53f7b_idx",
                ),
                migrations.RemoveIndex(
                    model_name="invoice",
                    name="user_accoun_kind_e004ab_idx",
                ),
                migrations.RemoveIndex(
                    model_name="invoice",
                    name="user_accoun_due_dat_385a3c_idx",
                ),
                migrations.RemoveIndex(
                    model_name="marketplacecelldailykpi",
                    name="user_accoun_day_836e22_idx",
                ),
                migrations.RemoveIndex(
                    model_name="marketplacecelldailykpi",
                    name="user_accoun_day_2c83c3_idx",
                ),
                migrations.RenameIndex(
                    model_name="communicationpreference",
                    new_name="user_accoun_user_id_d280da_idx",
                    old_name="ua_comm_user_scope_idx",
                ),
                migrations.RenameIndex(
                    model_name="communicationpreference",
                    new_name="user_accoun_busines_5a7871_idx",
                    old_name="ua_comm_business_scope_idx",
                ),
                migrations.RenameIndex(
                    model_name="emailverificationchallenge",
                    new_name="user_accoun_email_255441_idx",
                    old_name="ua_verify_email_purpose_idx",
                ),
                migrations.RenameIndex(
                    model_name="emailverificationchallenge",
                    new_name="user_accoun_expires_efa167_idx",
                    old_name="ua_verify_expires_idx",
                ),
                migrations.RenameIndex(
                    model_name="emailverificationchallenge",
                    new_name="user_accoun_created_445a8e_idx",
                    old_name="ua_verify_created_idx",
                ),
                migrations.RenameIndex(
                    model_name="invoicelineitem",
                    new_name="user_accoun_invoice_87ebd9_idx",
                    old_name="user_accoun_invoice_2969c5_idx",
                ),
                migrations.RenameIndex(
                    model_name="invoicelineitem",
                    new_name="user_accoun_invoice_ca6f39_idx",
                    old_name="user_accoun_invoice_9e4025_idx",
                ),
                migrations.RenameIndex(
                    model_name="servicecatalogitem",
                    new_name="user_accoun_busines_a01946_idx",
                    old_name="user_accoun_busines_8b88d9_idx",
                ),
                migrations.RenameIndex(
                    model_name="servicecatalogitem",
                    new_name="user_accoun_busines_a758d1_idx",
                    old_name="user_accoun_busines_1d1534_idx",
                ),
                migrations.RenameIndex(
                    model_name="servicecatalogitem",
                    new_name="user_accoun_busines_50ded8_idx",
                    old_name="user_accoun_busines_7268f7_idx",
                ),
                migrations.RenameIndex(
                    model_name="servicecatalogitem",
                    new_name="user_accoun_busines_7e62a7_idx",
                    old_name="user_accoun_busines_1b575f_idx",
                ),
                migrations.RenameIndex(
                    model_name="ticketconversationreadstate",
                    new_name="user_accoun_user_id_4996b1_idx",
                    old_name="ua_tcrs_user_scope_attention_idx",
                ),
                migrations.RenameIndex(
                    model_name="ticketconversationreadstate",
                    new_name="user_accoun_ticket__ad1e0c_idx",
                    old_name="ua_tcrs_ticket_scope_idx",
                ),

                # BusinessDailyKpi: state aligns to current model; DB legacy columns are preserved.
                migrations.RemoveField(model_name="businessdailykpi", name="cash_gmv"),
                migrations.RemoveField(model_name="businessdailykpi", name="gmv"),
                migrations.RemoveField(model_name="businessdailykpi", name="open_backlog"),
                migrations.RemoveField(model_name="businessdailykpi", name="platform_fee_collected"),
                migrations.RemoveField(model_name="businessdailykpi", name="platform_fee_due"),
                migrations.RemoveField(model_name="businessdailykpi", name="tickets_accepted"),
                migrations.RemoveField(model_name="businessdailykpi", name="tickets_assigned"),
                migrations.RemoveField(model_name="businessdailykpi", name="tickets_cancelled"),
                migrations.RemoveField(model_name="businessdailykpi", name="tickets_created"),
                migrations.AddField(
                    model_name="businessdailykpi",
                    name="gmv_paid",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                migrations.AddField(
                    model_name="businessdailykpi",
                    name="invoices_paid_count",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="businessdailykpi",
                    name="platform_fees_paid",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                migrations.AddField(
                    model_name="businessdailykpi",
                    name="tickets_paid",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="businessdailykpi",
                    name="tickets_total",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="businessdailykpi",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True),
                ),
                migrations.AlterField(
                    model_name="businessdailykpi",
                    name="day",
                    field=models.DateField(),
                ),
                migrations.AlterField(
                    model_name="businessdailykpi",
                    name="tickets_completed",
                    field=models.PositiveIntegerField(default=0),
                ),

                # Invoice: DB already aligned in Build 7C; this is state-only.
                migrations.RemoveField(model_name="invoice", name="amount_cents"),
                migrations.RemoveField(model_name="invoice", name="business"),
                migrations.RemoveField(model_name="invoice", name="created_by"),
                migrations.RemoveField(model_name="invoice", name="currency"),
                migrations.RemoveField(model_name="invoice", name="kind"),
                migrations.RemoveField(model_name="invoice", name="memo"),
                migrations.RemoveField(model_name="invoice", name="period_end"),
                migrations.RemoveField(model_name="invoice", name="period_start"),
                migrations.AddField(
                    model_name="invoice",
                    name="amount_paid",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="notes",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="payment_method",
                    field=models.CharField(
                        choices=[("CARD", "Card"), ("CASH", "Cash"), ("OTHER", "Other")],
                        default="CARD",
                        max_length=20,
                    ),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="platform_fee_amount",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="platform_fee_collected",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="platform_fee_collected_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="platform_fee_rate_bps",
                    field=models.PositiveIntegerField(default=100),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="stripe_charge_id",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="stripe_checkout_session_id",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="stripe_payment_intent_id",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="stripe_transfer_id",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="subtotal",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="tax",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="title",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="total",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True),
                ),
                migrations.AlterField(
                    model_name="invoice",
                    name="status",
                    field=models.CharField(
                        choices=[("DRAFT", "Draft"), ("SENT", "Sent"), ("PAID", "Paid"), ("VOID", "Void")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),

                # PlatformDailyKpi: state aligns to current model; DB legacy columns are preserved.
                migrations.RemoveField(model_name="platformdailykpi", name="active_businesses_30d"),
                migrations.RemoveField(model_name="platformdailykpi", name="businesses_created"),
                migrations.RemoveField(model_name="platformdailykpi", name="cash_gmv"),
                migrations.RemoveField(model_name="platformdailykpi", name="gmv"),
                migrations.RemoveField(model_name="platformdailykpi", name="marketplace_fill_rate"),
                migrations.RemoveField(model_name="platformdailykpi", name="marketplace_tickets_accepted"),
                migrations.RemoveField(model_name="platformdailykpi", name="marketplace_tickets_created"),
                migrations.RemoveField(model_name="platformdailykpi", name="open_backlog"),
                migrations.RemoveField(model_name="platformdailykpi", name="platform_fee_collected"),
                migrations.RemoveField(model_name="platformdailykpi", name="platform_fee_due"),
                migrations.RemoveField(model_name="platformdailykpi", name="signups"),
                migrations.RemoveField(model_name="platformdailykpi", name="tickets_cancelled"),
                migrations.RemoveField(model_name="platformdailykpi", name="tickets_created"),
                migrations.AddField(
                    model_name="platformdailykpi",
                    name="avg_response_time_seconds",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                migrations.AddField(
                    model_name="platformdailykpi",
                    name="businesses_total",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="platformdailykpi",
                    name="gmv_paid",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                migrations.AddField(
                    model_name="platformdailykpi",
                    name="invoices_paid_count",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="platformdailykpi",
                    name="platform_fees_paid",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                migrations.AddField(
                    model_name="platformdailykpi",
                    name="tickets_new",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="platformdailykpi",
                    name="tickets_paid",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="platformdailykpi",
                    name="tickets_total",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="platformdailykpi",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True),
                ),
                migrations.AddField(
                    model_name="platformdailykpi",
                    name="users_total",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AlterField(
                    model_name="platformdailykpi",
                    name="day",
                    field=models.DateField(unique=True),
                ),
                migrations.AlterField(
                    model_name="platformdailykpi",
                    name="tickets_completed",
                    field=models.PositiveIntegerField(default=0),
                ),

                # MarketplaceCellDailyKpi: state aligns to current model; DB legacy columns are preserved.
                migrations.AlterUniqueTogether(
                    name="marketplacecelldailykpi",
                    unique_together={("day", "zip_code", "category_key")},
                ),
                migrations.RemoveField(model_name="marketplacecelldailykpi", name="category_id"),
                migrations.RemoveField(model_name="marketplacecelldailykpi", name="fill_rate"),
                migrations.RemoveField(model_name="marketplacecelldailykpi", name="tickets_accepted"),
                migrations.RemoveField(model_name="marketplacecelldailykpi", name="zip_prefix"),
                migrations.AddField(
                    model_name="marketplacecelldailykpi",
                    name="category_key",
                    field=models.CharField(blank=True, default="", max_length=255),
                ),
                migrations.AddField(
                    model_name="marketplacecelldailykpi",
                    name="tickets_assigned",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="marketplacecelldailykpi",
                    name="tickets_completed",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="marketplacecelldailykpi",
                    name="tickets_declined",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="marketplacecelldailykpi",
                    name="tickets_viewed",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="marketplacecelldailykpi",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True),
                ),
                migrations.AddField(
                    model_name="marketplacecelldailykpi",
                    name="zip_code",
                    field=models.CharField(blank=True, default="", max_length=10),
                ),
                migrations.AlterField(
                    model_name="marketplacecelldailykpi",
                    name="day",
                    field=models.DateField(),
                ),
                migrations.AlterField(
                    model_name="marketplacecelldailykpi",
                    name="tickets_created",
                    field=models.PositiveIntegerField(default=0),
                ),

                migrations.AlterField(
                    model_name="user",
                    name="is_platform_admin",
                    field=models.BooleanField(
                        default=False,
                        help_text="Internal platform administration access.",
                    ),
                ),
                migrations.AddIndex(
                    model_name="invoice",
                    index=models.Index(fields=["status", "created_at"], name="user_accoun_status_ad892d_idx"),
                ),
                migrations.AddIndex(
                    model_name="invoice",
                    index=models.Index(fields=["payment_method", "status"], name="user_accoun_payment_0dd4fd_idx"),
                ),
                migrations.AddIndex(
                    model_name="ticket",
                    index=models.Index(fields=["is_marketplace", "created_at"], name="user_accoun_is_mark_274b8e_idx"),
                ),
                migrations.AddIndex(
                    model_name="ticket",
                    index=models.Index(fields=["is_marketplace", "status"], name="user_accoun_is_mark_4e9fd2_idx"),
                ),
            ],
        ),
    ]