from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_accounts", "0120_platformuserclassification"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("PLAID", "Plaid"), ("MANUAL", "Manual")], default="PLAID", max_length=24)),
                ("provider_item_id", models.CharField(blank=True, default="", max_length=255)),
                ("institution_id", models.CharField(blank=True, default="", max_length=120)),
                ("institution_name", models.CharField(blank=True, default="", max_length=180)),
                ("encrypted_access_token", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("NEEDS_ATTENTION", "Needs attention"), ("DISCONNECTED", "Disconnected")], default="ACTIVE", max_length=24)),
                ("cursor", models.TextField(blank=True, default="")),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="finance_connections", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="FinanceAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider_account_id", models.CharField(blank=True, default="", max_length=255)),
                ("name", models.CharField(max_length=180)),
                ("official_name", models.CharField(blank=True, default="", max_length=255)),
                ("kind", models.CharField(choices=[("CHECKING", "Checking"), ("SAVINGS", "Savings"), ("CREDIT_CARD", "Credit card"), ("MORTGAGE", "Mortgage"), ("STUDENT_LOAN", "Student loan"), ("AUTO_LOAN", "Auto loan"), ("PERSONAL_LOAN", "Personal loan"), ("INVESTMENT", "Investment"), ("OTHER", "Other")], default="OTHER", max_length=32)),
                ("mask", models.CharField(blank=True, default="", max_length=12)),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("current_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("available_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("credit_limit", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("is_manual", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("connection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="accounts", to="user_accounts.financeconnection")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="finance_accounts", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["kind", "name"]},
        ),
        migrations.CreateModel(
            name="FinanceGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("EMERGENCY_FUND", "Emergency fund"), ("DEBT_PAYOFF", "Debt payoff"), ("SAVINGS", "Savings"), ("PURCHASE", "Purchase"), ("INVESTMENT", "Investment"), ("OTHER", "Other")], default="OTHER", max_length=32)),
                ("name", models.CharField(max_length=180)),
                ("target_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("current_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("priority", models.PositiveSmallIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="finance_goals", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["priority", "target_date", "name"]},
        ),
        migrations.CreateModel(
            name="FinanceLiability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("kind", models.CharField(choices=[("CREDIT_CARD", "Credit card"), ("MORTGAGE", "Mortgage"), ("STUDENT_LOAN", "Student loan"), ("AUTO_LOAN", "Auto loan"), ("PERSONAL_LOAN", "Personal loan"), ("OTHER", "Other")], default="OTHER", max_length=32)),
                ("lender", models.CharField(blank=True, default="", max_length=180)),
                ("outstanding_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("original_principal", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("minimum_payment", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("next_payment_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("next_payment_date", models.DateField(blank=True, null=True)),
                ("apr", models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ("interest_rate", models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ("origination_date", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("payoff_target_date", models.DateField(blank=True, null=True)),
                ("last_payment_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("last_payment_date", models.DateField(blank=True, null=True)),
                ("property_address", models.CharField(blank=True, default="", max_length=320)),
                ("escrow_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("is_manual", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="liability", to="user_accounts.financeaccount")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="finance_liabilities", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["next_payment_date", "name"]},
        ),
        migrations.CreateModel(
            name="FinanceObligation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=180)),
                ("category", models.CharField(choices=[("HOUSING", "Housing"), ("UTILITIES", "Utilities"), ("INSURANCE", "Insurance"), ("TRANSPORTATION", "Transportation"), ("SUBSCRIPTIONS", "Subscriptions"), ("DEBT", "Debt"), ("CHILDCARE", "Childcare"), ("HEALTH", "Health"), ("TAX", "Tax"), ("OTHER", "Other")], default="OTHER", max_length=32)),
                ("merchant", models.CharField(blank=True, default="", max_length=180)),
                ("expected_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("minimum_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("due_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("autopay", models.BooleanField(default=False)),
                ("recurring", models.BooleanField(default=True)),
                ("cadence", models.CharField(blank=True, default="MONTHLY", max_length=32)),
                ("active", models.BooleanField(default=True)),
                ("is_manual", models.BooleanField(default=True)),
                ("provider_stream_id", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("linked_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="obligations", to="user_accounts.financeaccount")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="finance_obligations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["next_due_date", "due_day", "name"]},
        ),
        migrations.CreateModel(
            name="FinanceTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider_transaction_id", models.CharField(blank=True, default="", max_length=255)),
                ("merchant_name", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.CharField(blank=True, default="", max_length=320)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("date", models.DateField()),
                ("pending", models.BooleanField(default=False)),
                ("category_primary", models.CharField(blank=True, default="", max_length=100)),
                ("category_detailed", models.CharField(blank=True, default="", max_length=160)),
                ("is_income", models.BooleanField(default=False)),
                ("is_transfer", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="user_accounts.financeaccount")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="finance_transactions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.AddConstraint(model_name="financeconnection", constraint=models.UniqueConstraint(fields=("user", "provider", "provider_item_id"), name="uniq_user_finance_provider_item")),
        migrations.AddConstraint(model_name="financeaccount", constraint=models.UniqueConstraint(condition=~models.Q(("provider_account_id", "")), fields=("user", "provider_account_id"), name="uniq_user_finance_provider_account")),
        migrations.AddIndex(model_name="financetransaction", index=models.Index(fields=["user", "-date"], name="user_accoun_user_id_74b808_idx")),
        migrations.AddIndex(model_name="financetransaction", index=models.Index(fields=["user", "category_primary"], name="user_accoun_user_id_4e38cf_idx")),
        migrations.AddConstraint(model_name="financetransaction", constraint=models.UniqueConstraint(condition=~models.Q(("provider_transaction_id", "")), fields=("user", "provider_transaction_id"), name="uniq_user_finance_provider_transaction")),
    ]
