# Generated by Django for SyncWorks Sports Analytics

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("platform_sports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameCastShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("enabled", models.BooleanField(default=False)),
                ("show_player_stats", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sports_gamecast_shares_created", to=settings.AUTH_USER_MODEL)),
                ("game", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="gamecast_share", to="platform_sports.sportsgame")),
            ],
            options={"ordering": ("-updated_at", "-id")},
        ),
        migrations.CreateModel(
            name="SoftballPlayContext",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("batted_ball_type", models.CharField(blank=True, choices=[("GROUND", "Ground ball"), ("LINE", "Line drive"), ("FLY", "Fly ball"), ("POP", "Pop up")], max_length=12)),
                ("spray_zone", models.CharField(blank=True, choices=[("LEFT_LINE", "Left-field line"), ("LEFT", "Left field"), ("LEFT_CENTER", "Left center"), ("CENTER", "Center field"), ("RIGHT_CENTER", "Right center"), ("RIGHT", "Right field"), ("RIGHT_LINE", "Right-field line"), ("INFIELD_LEFT", "Left infield"), ("INFIELD_MIDDLE", "Middle infield"), ("INFIELD_RIGHT", "Right infield")], max_length=20)),
                ("spray_x", models.DecimalField(blank=True, decimal_places=2, help_text="Normalized field X coordinate from 0 to 100.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("spray_y", models.DecimalField(blank=True, decimal_places=2, help_text="Normalized field Y coordinate from 0 to 100.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("runner_on_first_before", models.BooleanField(default=False)),
                ("runner_on_second_before", models.BooleanField(default=False)),
                ("runner_on_third_before", models.BooleanField(default=False)),
                ("runners_advanced", models.PositiveSmallIntegerField(default=0)),
                ("productive_out", models.BooleanField(default=False)),
                ("quality_note", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="softball_play_context_created", to=settings.AUTH_USER_MODEL)),
                ("plate_appearance", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="advanced_context", to="platform_sports.softballplateappearance")),
            ],
            options={"ordering": ("plate_appearance__game_id", "plate_appearance__sequence")},
        ),
        migrations.AddIndex(
            model_name="softballplaycontext",
            index=models.Index(fields=["spray_zone", "batted_ball_type"], name="sports_ctx_spray_type"),
        ),
    ]
