from __future__ import annotations

DEFAULT_AFFILIATE_COMMISSION_RATE_BPS = 1000
DEFAULT_AFFILIATE_CODE_PREFIX = "SWSC"
DEFAULT_AGREEMENT_VERSION = "2026-05-20-v1"

SYNCWORKS_BASE_REFERRAL_PATH = "/register"